//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _PKCheckErrorRecoveryAttempter : NSObject
{
    CDUnknownBlockType _action;	// 8 = 0x8
}

- (void)attemptRecoveryFromError:(id)arg1 optionIndex:(unsigned long long)arg2 delegate:(id)arg3 didRecoverSelector:(SEL)arg4 contextInfo:(void *)arg5;	// IMP=0x000000000006bbae
- (BOOL)attemptRecoveryFromError:(id)arg1 optionIndex:(unsigned long long)arg2;	// IMP=0x000000000006bb7f
- (void)dealloc;	// IMP=0x000000000006bb18
- (id)initWithAction:(CDUnknownBlockType)arg1;	// IMP=0x000000000006ba9f

@end

