//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PKInstallServiceClient.h"

@class NSObject<OS_dispatch_semaphore>, NSString, NSXPCConnection;

@interface _PKInstallClientConnection : NSObject <PKInstallServiceClient>
{
    NSXPCConnection *_connection;	// 8 = 0x8
    id <PKInstallService> _proxy;	// 16 = 0x10
    id <PKInstallService> _blockingProxy;	// 24 = 0x18
    NSObject<OS_dispatch_semaphore> *_sema;	// 32 = 0x20
    BOOL _isSilent;	// 40 = 0x28
}

@property(setter=setSilent:) BOOL isSilent; // @synthesize isSilent=_isSilent;
- (void)installDidEndForToken:(id)arg1;	// IMP=0x0000000000005550
- (void)installDidBeginCommitForToken:(id)arg1;	// IMP=0x000000000000554a
- (void)installDidBeginForToken:(id)arg1;	// IMP=0x0000000000005544
- (void)invalidate;	// IMP=0x00000000000054d5
- (BOOL)waitUntilDoneOrTimedOut;	// IMP=0x0000000000005467
- (BOOL)waitUntilDone;	// IMP=0x0000000000005445
- (void)signal;	// IMP=0x0000000000005430
- (id)blockingProxy;	// IMP=0x00000000000052b8
- (id)proxy;	// IMP=0x000000000000518d
- (BOOL)isServiceRemote;	// IMP=0x0000000000005175
- (BOOL)connectToDaemon:(BOOL)arg1 privileged:(BOOL)arg2 clientObject:(id)arg3;	// IMP=0x0000000000004de0
- (void)dealloc;	// IMP=0x0000000000004d44
- (id)init;	// IMP=0x0000000000004cdb

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

