//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface _PKPackageCreationFileDigest : NSObject
{
    NSString *_path;	// 8 = 0x8
    NSString *_digest;	// 16 = 0x10
}

- (id)digest;	// IMP=0x00000000000265c1
- (void)dealloc;	// IMP=0x000000000002653a
- (id)initWithPath:(id)arg1;	// IMP=0x00000000000264c1

@end

