//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBundle.h"

@interface NSBundle (CodeSigningAdditions)
- (BOOL)_verifyCodeSignaturesWithRequirement:(struct __SecRequirement *)arg1 recursively:(BOOL)arg2 errors:(id *)arg3 cancelUsingTest:(CDUnknownBlockType)arg4;	// IMP=0x0000000000075ab9
- (BOOL)_verifyCodeSignaturesWithRequirement:(struct __SecRequirement *)arg1 recursively:(BOOL)arg2 errors:(id *)arg3;	// IMP=0x0000000000075aa4
@end

