//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBundle.h"

@interface NSBundle (CodeSigningAdditionsPrivate)
- (BOOL)__verifyCodeSignatureOnURL:(id)arg1 requirements:(struct __SecRequirement *)arg2 error:(id *)arg3;	// IMP=0x00000000000761b9
- (BOOL)__verifyCodeSignaturesUnderDirectory:(id)arg1 requirements:(struct __SecRequirement *)arg2 currentBundleResourcePath:(id)arg3 addingErrorsTo:(id)arg4 cancelUsingTest:(CDUnknownBlockType)arg5;	// IMP=0x0000000000075ca5
- (BOOL)__verifyCodeSignaturesWithRequirement:(struct __SecRequirement *)arg1 recursively:(BOOL)arg2 addingErrorsTo:(id)arg3 cancelUsingTest:(CDUnknownBlockType)arg4;	// IMP=0x0000000000075b46
@end

