//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (BomPathAdditions)
+ (id)_commonParentOfPaths:(id)arg1;	// IMP=0x000000000002c9d3
- (BOOL)_isAppleDoublePath;	// IMP=0x000000000002c9a1
- (id)_appleDoublePath;	// IMP=0x000000000002c918
- (id)_relativeStringByDeletingBomPathPrefix;	// IMP=0x000000000002c8d2
- (id)_relativeString;	// IMP=0x000000000002c87e
- (id)_absoluteStringByDeletingBomPathPrefix;	// IMP=0x000000000002c838
- (id)_absoluteString;	// IMP=0x000000000002c7e2
- (id)_stringByInsertingBomPathPrefix;	// IMP=0x000000000002c77f
@end

