//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSXMLNode.h"

@interface NSXMLNode (PKAdditions)
- (void)_setBool:(BOOL)arg1;	// IMP=0x000000000002da67
- (BOOL)_boolValue;	// IMP=0x000000000002da35
@end

