//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSXMLElement.h"

@interface NSXMLElement (PKAdditions)
- (void)_setStringValueAsCDATA:(id)arg1;	// IMP=0x000000000002d9ac
- (BOOL)_hasChildElements;	// IMP=0x000000000002d899
- (BOOL)_hasPureTextContent;	// IMP=0x000000000002d74f
- (id)_trimmedStringValue;	// IMP=0x000000000002d70d
- (void)_removeChildren:(id)arg1;	// IMP=0x000000000002d4d6
- (void)_replaceAttributesAsDictionary:(id)arg1;	// IMP=0x000000000002d482
- (id)_attributesDictionary;	// IMP=0x000000000002d2ea
- (void)_setBool:(BOOL)arg1 forAttributeName:(id)arg2;	// IMP=0x000000000002d2c4
- (void)_setString:(id)arg1 forAttributeName:(id)arg2;	// IMP=0x000000000002d25a
- (id)_attributeForName:(id)arg1 ofAnyElementNamed:(id)arg2;	// IMP=0x000000000002d1e6
- (id)_elementsForName:(id)arg1 identifier:(id)arg2;	// IMP=0x000000000002d045
- (id)_lastElementForName:(id)arg1 createIfNeeded:(BOOL)arg2;	// IMP=0x000000000002cfb3
@end

