//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@interface PKAddExtendedAttributesInstallOperation : PKInstallOperation
{
}

- (void)main;	// IMP=0x0000000000060ab5
- (void)_applyAttributesForSepcifier:(id)arg1;	// IMP=0x00000000000606f7
- (int)installState;	// IMP=0x00000000000606ec

@end

