//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@interface PKAddRestrictedRootFlagInstallOperation : PKInstallOperation
{
}

- (void)main;	// IMP=0x000000000006c145
- (id)messageTracerComment;	// IMP=0x000000000006bf75
- (id)messageTracerDomain;	// IMP=0x000000000006bf68
- (int)installState;	// IMP=0x000000000006bf5d

@end

