//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PKArchiveSigner : NSObject
{
    NSString *_algorithmType;	// 8 = 0x8
    struct OpaqueSecKeyRef *_privateKeyRef;	// 16 = 0x10
    unsigned long long _signing_context;	// 24 = 0x18
    struct _CMSEncoder *_encoder;	// 32 = 0x20
    struct __CFDictionary *_tsaContext;	// 40 = 0x28
    int _signatureSize;	// 48 = 0x30
}

- (id)signatureDataBySigningData:(id)arg1;	// IMP=0x000000000000ba8c
- (void)setSignatureSize:(int)arg1;	// IMP=0x000000000000ba7c
- (int)signatureSize;	// IMP=0x000000000000b97b
- (void)dealloc;	// IMP=0x000000000000b8c0
- (id)initWithSigningIdentity:(struct OpaqueSecIdentityRef *)arg1 algorithm:(id)arg2 usingTSAIfSupported:(BOOL)arg3;	// IMP=0x000000000000b5b4

@end

