//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKMutableDistributionContainer.h>

@class NSDictionary, PKArchive;

@interface PKArchiveDistributionContainer : PKMutableDistributionContainer
{
    PKArchive *_archive;	// 24 = 0x18
    NSDictionary *_lprojSubpathByName;	// 32 = 0x20
    NSDictionary *_strings;	// 40 = 0x28
}

- (BOOL)commitReturningError:(id *)arg1;	// IMP=0x0000000000057e33
- (BOOL)setResourceData:(id)arg1 forKey:(id)arg2 forLocalization:(id)arg3;	// IMP=0x0000000000057c93
- (BOOL)setStringsData:(id)arg1 forLocalization:(id)arg2;	// IMP=0x0000000000057c1e
- (BOOL)setDistributionFromContainer:(id)arg1;	// IMP=0x0000000000057b51
- (id)_resourceDataForKey:(id)arg1;	// IMP=0x00000000000578d5
- (id)localizedStringForKey:(id)arg1 value:(id)arg2;	// IMP=0x000000000005788b
- (id)stringsDictionary;	// IMP=0x000000000005762c
- (id)_lprojSubpathByName;	// IMP=0x00000000000573dd
- (void)dealloc;	// IMP=0x0000000000057345
- (id)initWithArchive:(id)arg1 forWriting:(BOOL)arg2 error:(id *)arg3;	// IMP=0x0000000000057126

@end

