//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface PKArchive : NSObject
{
}

+ (id)archiveWithPath:(id)arg1;	// IMP=0x000000000000a097
+ (id)_allArchiveClasses;	// IMP=0x000000000000a018
- (BOOL)closeArchive;	// IMP=0x000000000000a4ca
- (BOOL)fileExistsAtPath:(id)arg1;	// IMP=0x000000000000a4ae
- (BOOL)verifyReturningError:(id *)arg1;	// IMP=0x000000000000a47b
- (id)fileAttributesAtPath:(id)arg1;	// IMP=0x000000000000a448
- (BOOL)extractItemAtPath:(id)arg1 toPath:(id)arg2 error:(id *)arg3;	// IMP=0x000000000000a314
- (id)dataForPath:(id)arg1;	// IMP=0x000000000000a2e1
- (id)enumeratorAtPath:(id)arg1;	// IMP=0x000000000000a2ae
- (id)archiveDigest;	// IMP=0x000000000000a2a6
- (id)archivePath;	// IMP=0x000000000000a273
- (id)description;	// IMP=0x000000000000a213
- (BOOL)_extractFile:(id)arg1 toPath:(id)arg2 error:(id *)arg3;	// IMP=0x000000000000a530
- (id)initForReadingFromPath:(id)arg1;	// IMP=0x000000000000a4fd
- (id)archiveSignatureDate;	// IMP=0x000000000000a704
- (id)archiveSignatures;	// IMP=0x000000000000a6fc

@end

