//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface PKBOM : NSObject
{
    NSData *_bomData;	// 8 = 0x8
    struct _BOMBom *_BOMBom;	// 16 = 0x10
}

+ (BOOL)_setAttributes:(id)arg1 ofBOMFSObject:(struct _BOMFSObject *)arg2;	// IMP=0x000000000001b95d
+ (id)_attributesOfBOMFSObject:(struct _BOMFSObject *)arg1;	// IMP=0x000000000001b72f
+ (id)_NSFileTypeFromBOMFSObjType:(int)arg1;	// IMP=0x000000000001b708
- (unsigned long long)totalSize;	// IMP=0x000000000001be7b
- (unsigned long long)fileCount;	// IMP=0x000000000001be5c
- (id)subpathsOfDirectoryAtPath:(id)arg1;	// IMP=0x000000000001bd00
- (id)directoryEnumerator;	// IMP=0x000000000001bcbb
- (id)attributesOfItemAtPath:(id)arg1;	// IMP=0x000000000001bbca
- (struct _BOMBom *)BOMBom;	// IMP=0x000000000001b6f7
- (void)dealloc;	// IMP=0x000000000001b67b
- (id)initWithBOMData:(id)arg1;	// IMP=0x000000000001b55d
- (id)initWithBOMPath:(id)arg1;	// IMP=0x000000000001b494

@end

