//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDirectoryEnumerator.h"

@class PKBOM;

@interface PKBOMDirectoryEnumerator : NSDirectoryEnumerator
{
    PKBOM *_pkBom;	// 8 = 0x8
    struct _BOMBomEnumerator *_be;	// 16 = 0x10
    struct _BOMFSObject *_currentFSO;	// 24 = 0x18
}

- (id)fileAttributes;	// IMP=0x000000000001cc37
- (BOOL)isDirectory;	// IMP=0x000000000001cc18
- (void)skipDescendents;	// IMP=0x000000000001cc06
- (void)skipDescendants;	// IMP=0x000000000001cbf1
- (id)nextObject;	// IMP=0x000000000001cba4
- (void)dealloc;	// IMP=0x000000000001cb13
- (id)initWithBOM:(id)arg1;	// IMP=0x000000000001c9fd

@end

