//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKComponent.h>

@class NSString, PKBundleComponentVersion;

@interface PKBundleComponent : PKComponent
{
    NSString *_storageType;	// 112 = 0x70
    NSString *_bundlePath;	// 120 = 0x78
    BOOL _onDisk;	// 128 = 0x80
    PKBundleComponentVersion *_bundleVersion;	// 136 = 0x88
    int _overwriteAction;	// 144 = 0x90
}

+ (void)enumerateBundleComponentsUnderRoot:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x000000000001dd58
+ (BOOL)_enumerateBundleComponentsUnderURL:(id)arg1 relativeToRoot:(id)arg2 parentComponent:(id)arg3 usingBlock:(CDUnknownBlockType)arg4;	// IMP=0x000000000001e470
@property int overwriteAction; // @synthesize overwriteAction=_overwriteAction;
- (id)bundleName;	// IMP=0x000000000001dad2
- (id)bundlePath;	// IMP=0x000000000001dac1
- (id)storageType;	// IMP=0x000000000001dab0
- (id)subpaths;	// IMP=0x000000000001d8f6
- (id)prefixPath;	// IMP=0x000000000001d8b2
- (long long)versionCompare:(id)arg1;	// IMP=0x000000000001d7e0
- (id)bundleVersion;	// IMP=0x000000000001d7cf
- (void)dealloc;	// IMP=0x000000000001d737
- (id)initWithBundleAtPath:(id)arg1 relativeToDestination:(id)arg2;	// IMP=0x000000000001d505
- (id)initWithIdentifier:(id)arg1 versionAttributes:(id)arg2 bundlePath:(id)arg3 storageType:(id)arg4;	// IMP=0x000000000001d3d6
- (id)initWithIdentifier:(id)arg1 versionAttributes:(id)arg2 bundlePath:(id)arg3;	// IMP=0x000000000001d3c1
- (id)_bundle;	// IMP=0x000000000001e3d3

@end

