//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PKBundleComponentVersion : NSObject
{
    NSString *_shortVersionString;	// 8 = 0x8
    NSString *_origShortVersionString;	// 16 = 0x10
    NSString *_bundleVersion;	// 24 = 0x18
    NSString *_origBundleVersion;	// 32 = 0x20
    NSString *_sourceVersion;	// 40 = 0x28
    NSString *_buildVersion;	// 48 = 0x30
    BOOL _isOnDisk;	// 56 = 0x38
}

+ (id)_orderedVersionKeys;	// IMP=0x000000000004b499
+ (id)_standardizedTupleVersionString:(id)arg1;	// IMP=0x000000000004b2a9
+ (id)_combinedVersionAndInfoDictionaryForCFBundle:(struct __CFBundle *)arg1;	// IMP=0x000000000004b167
+ (id)_combinedVersionAndInfoDictionaryForBundle:(id)arg1;	// IMP=0x000000000004b10c
+ (id)bundleComponentVersionWithOnDiskCFBundle:(struct __CFBundle *)arg1;	// IMP=0x000000000004a7d6
+ (id)bundleComponentVersionWithOnDiskBundle:(id)arg1;	// IMP=0x000000000004a76d
+ (id)bundleComponentVersionWithPackageAttributes:(id)arg1;	// IMP=0x000000000004a723
- (id)combinedVersionString;	// IMP=0x000000000004af6a
- (id)attributeDictionary;	// IMP=0x000000000004ae9f
- (BOOL)_isOnDiskComponent;	// IMP=0x000000000004ae8e
- (id)buildVersion;	// IMP=0x000000000004ae7d
- (id)sourceVersion;	// IMP=0x000000000004ae6c
- (id)bundleVersion;	// IMP=0x000000000004ae5b
- (id)shortVersionString;	// IMP=0x000000000004ae4a
- (long long)compare:(id)arg1;	// IMP=0x000000000004ac5c
- (id)description;	// IMP=0x000000000004abfc
- (void)dealloc;	// IMP=0x000000000004ab31
- (id)initWithAttributes:(id)arg1 forOnDiskComponent:(BOOL)arg2;	// IMP=0x000000000004aa88
- (id)initWithShortVersionString:(id)arg1 bundleVersion:(id)arg2 sourceVersion:(id)arg3 buildVersion:(id)arg4 forOnDiskComponent:(BOOL)arg5;	// IMP=0x000000000004a83f

@end

