//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface PKBundleStorage : NSObject
{
    NSString *_path;	// 8 = 0x8
    NSString *_storageType;	// 16 = 0x10
    NSString *_identifier;	// 24 = 0x18
    NSDictionary *_versionAttributes;	// 32 = 0x20
}

+ (id)bundleStorageWithPath:(id)arg1;	// IMP=0x0000000000076b7e
+ (id)_allStorageClasses;	// IMP=0x0000000000076b1e
- (id)versionAttributes;	// IMP=0x0000000000077091
- (id)identifier;	// IMP=0x0000000000077080
- (id)storageType;	// IMP=0x000000000007706f
- (id)description;	// IMP=0x0000000000076f79
- (void)dealloc;	// IMP=0x0000000000076ed0
- (id)_initWithPath:(id)arg1 storageType:(id)arg2 identifier:(id)arg3 versionAttributes:(id)arg4;	// IMP=0x0000000000076dd2
- (id)_initWithPath:(id)arg1 fileAttributes:(id)arg2;	// IMP=0x0000000000076d9f

@end

