//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@class NSString;

@interface PKCleanEFWCacheInstallOperation : PKInstallOperation
{
    NSString *_cacheTool;	// 80 = 0x50
}

- (void)main;	// IMP=0x0000000000071e9a
- (int)installState;	// IMP=0x0000000000071e8f
- (void)dealloc;	// IMP=0x0000000000071e28
- (id)initWithRequest:(id)arg1 sandbox:(id)arg2 analyzer:(id)arg3;	// IMP=0x0000000000071cfc

@end

