//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, PKPackage;

@interface PKComponent : NSObject
{
    NSString *identifier;	// 8 = 0x8
    NSString *version;	// 16 = 0x10
    NSString *prefixPath;	// 24 = 0x18
    BOOL relocatable;	// 32 = 0x20
    BOOL versionChecked;	// 33 = 0x21
    BOOL strictIdentifier;	// 34 = 0x22
    NSArray *subpaths;	// 40 = 0x28
    PKPackage *package;	// 48 = 0x30
    NSString *destinationPath;	// 56 = 0x38
    NSMutableDictionary *_scriptsDictionary;	// 64 = 0x40
    NSMutableDictionary *_pathToPatchInfoDictionary;	// 72 = 0x48
    NSMutableDictionary *_pathToRequiredFilesDictionary;	// 80 = 0x50
    NSMutableArray *_deferredInstallPaths;	// 88 = 0x58
    NSMutableSet *_doNotObsoletePaths;	// 96 = 0x60
    NSMutableSet *_doNotObsoletePrefixes;	// 104 = 0x68
}

+ (BOOL)isInstallablePath:(id)arg1;	// IMP=0x000000000001db86
+ (id)findComponentsWithIdentifier:(id)arg1 version:(id)arg2 destination:(id)arg3;	// IMP=0x000000000001db37
+ (id)findComponentsWithIdentifier:(id)arg1 destination:(id)arg2;	// IMP=0x000000000001db1d
+ (id)_findComponentsViaSpotlightWithIdentifier:(id)arg1 version:(id)arg2 destination:(id)arg3;	// IMP=0x000000000001e06f
+ (id)_findComponentViaLaunchServicesWithIdentifier:(id)arg1 version:(id)arg2 destination:(id)arg3;	// IMP=0x000000000001df4f
+ (BOOL)_bundleAtPath:(id)arg1 matchesVersion:(id)arg2;	// IMP=0x000000000001debd
+ (BOOL)_componentPath:(id)arg1 matchesDestination:(id)arg2;	// IMP=0x000000000001de3d
@property(retain) NSArray *subpaths; // @synthesize subpaths;
@property BOOL strictIdentifier; // @synthesize strictIdentifier;
@property BOOL versionChecked; // @synthesize versionChecked;
@property BOOL relocatable; // @synthesize relocatable;
@property(retain) NSString *prefixPath; // @synthesize prefixPath;
@property(retain) NSString *version; // @synthesize version;
@property(retain) NSString *identifier; // @synthesize identifier;
- (long long)versionCompare:(id)arg1;	// IMP=0x000000000001d26f
- (long long)compare:(id)arg1;	// IMP=0x000000000001d1f6
- (BOOL)isEqual:(id)arg1;	// IMP=0x000000000001d184
- (unsigned long long)hash;	// IMP=0x000000000001d159
- (void)setScript:(id)arg1 forType:(id)arg2;	// IMP=0x000000000001d0e5
- (id)scriptForType:(id)arg1;	// IMP=0x000000000001d0c8
@property(retain) NSString *destinationPath; // @synthesize destinationPath;
@property PKPackage *package; // @synthesize package;
- (id)description;	// IMP=0x000000000001cf88
- (id)componentKey;	// IMP=0x000000000001cf28
- (void)dealloc;	// IMP=0x000000000001ce06
- (id)initWithIdentifier:(id)arg1 version:(id)arg2;	// IMP=0x000000000001cc64
- (id)_doNotObsoletePrefixes;	// IMP=0x000000000001de1b
- (id)_doNotObsoletePaths;	// IMP=0x000000000001de0a
- (id)_pathToRequiredFilesDictionary;	// IMP=0x000000000001ddf9
- (id)_pathToPatchInfoDictionary;	// IMP=0x000000000001dde8
- (id)_deferredInstallPaths;	// IMP=0x000000000001ddd7
- (id)_scriptsDictionary;	// IMP=0x000000000001de2c

@end

