//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PKDeferredInstallManager : NSObject
{
    NSString *_destinationPath;	// 8 = 0x8
    NSString *_rootPath;	// 16 = 0x10
    unsigned long long _options;	// 24 = 0x18
    NSString *_manifestPath;	// 32 = 0x20
}

@property unsigned long long options; // @synthesize options=_options;
- (BOOL)prepareWithDeferredFileList:(id)arg1 error:(id *)arg2;	// IMP=0x00000000000875dc
- (BOOL)addScriptAtPath:(id)arg1 error:(id *)arg2;	// IMP=0x00000000000875be
- (id)rootPath;	// IMP=0x0000000000087588
- (void)dealloc;	// IMP=0x00000000000874f0
- (id)initWithDestinationPath:(id)arg1 systemContentManifestPath:(id)arg2 error:(id *)arg3;	// IMP=0x000000000008730d
- (id)initWithDestinationPath:(id)arg1 error:(id *)arg2;	// IMP=0x00000000000872f3

@end

