//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, NSXMLElement, PKDistribution;

@interface PKDistributionChoice : NSObject
{
    PKDistribution *_distribution;	// 8 = 0x8
    NSString *_identifier;	// 16 = 0x10
    NSArray *_choiceElements;	// 24 = 0x18
    NSXMLElement *_referencingElement;	// 32 = 0x20
    NSArray *_pkgRefIdentifiers;	// 40 = 0x28
}

- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;	// IMP=0x0000000000050182
- (id)valueForUndefinedKey:(id)arg1;	// IMP=0x000000000005011a
- (id)scriptForAttributeName:(id)arg1 createIfNeeded:(BOOL)arg2;	// IMP=0x000000000004fdf8
- (id)scriptForAttributeName:(id)arg1;	// IMP=0x000000000004fde4
- (void)setValue:(id)arg1 forAttributeName:(id)arg2;	// IMP=0x000000000004fcd9
- (id)valueForAttributeName:(id)arg1;	// IMP=0x000000000004fb2a
- (id)packageIdentifiers;	// IMP=0x000000000004f978
- (BOOL)validatePackageReference:(id *)arg1 error:(id *)arg2;	// IMP=0x000000000004f7bc
- (void)removePackageReferencesObject:(id)arg1;	// IMP=0x000000000004f291
- (void)addPackageReferencesObject:(id)arg1;	// IMP=0x000000000004f0f0
- (id)memberOfPackageReferences:(id)arg1;	// IMP=0x000000000004f085
- (id)enumeratorOfPackageReferences;	// IMP=0x000000000004ef12
- (unsigned long long)countOfPackageReferences;	// IMP=0x000000000004eee7
- (void)_invalidatePkgRefIdentifiers;	// IMP=0x000000000004ee17
- (id)_pkgRefIdentifiers;	// IMP=0x000000000004ea39
- (void)removeObjectFromChildrenAtIndex:(unsigned long long)arg1;	// IMP=0x000000000004e889
- (void)insertObject:(id)arg1 inChildrenAtIndex:(unsigned long long)arg2;	// IMP=0x000000000004e24b
- (id)objectInChildrenAtIndex:(unsigned long long)arg1;	// IMP=0x000000000004e11d
- (unsigned long long)countOfChildren;	// IMP=0x000000000004e0e0
- (id)distribution;	// IMP=0x000000000004e0cf
- (BOOL)validateIdentifier:(id *)arg1 error:(id *)arg2;	// IMP=0x000000000004def7
- (void)setIdentifier:(id)arg1;	// IMP=0x000000000004dd26
- (id)identifier;	// IMP=0x000000000004dd15
- (id)description;	// IMP=0x000000000004dcb5
- (BOOL)_validateChoice;	// IMP=0x000000000004da28
- (void)dealloc;	// IMP=0x000000000004d97f
- (id)init;	// IMP=0x000000000004d969
- (id)_initWithDistribution:(id)arg1 referencingElement:(id)arg2;	// IMP=0x000000000004d7ab

@end

