//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PKDistribution;

@interface PKDistributionContainer : NSObject
{
    PKDistribution *_distribution;	// 8 = 0x8
}

+ (id)localizationNamesAtPath:(id)arg1;	// IMP=0x0000000000056017
+ (id)_lprojSubpathsInDirectory:(id)arg1;	// IMP=0x0000000000055f46
- (id)resourceDataForKey:(id)arg1 returningMIMEType:(id *)arg2 returningUTI:(id *)arg3;	// IMP=0x0000000000055e96
- (id)_resourceContentType:(id)arg1 forKey:(id)arg2;	// IMP=0x0000000000055d9b
- (id)_resourceDataForKey:(id)arg1;	// IMP=0x0000000000055d68
- (id)localizedStringForKey:(id)arg1 value:(id)arg2;	// IMP=0x0000000000055d35
- (id)stringsDictionary;	// IMP=0x0000000000055d02
- (id)distribution;	// IMP=0x0000000000055cf1
- (void)dealloc;	// IMP=0x0000000000055c8a
- (id)initWithArchive:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000055c39
- (id)initWithPath:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000055be8
- (id)initWithDistributionData:(id)arg1 distributionURL:(id)arg2 error:(id *)arg3;	// IMP=0x0000000000055b94
- (id)_initWithDistributionData:(id)arg1 distributionURL:(id)arg2 error:(id *)arg3;	// IMP=0x0000000000055ab3

@end

