//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSMutableArray, NSMutableDictionary, NSXMLDocument;

@interface PKDistribution : NSObject <NSSecureCoding, NSCopying>
{
    NSXMLDocument *_xmlDocument;	// 8 = 0x8
    NSMutableDictionary *_choicesByIdentifier;	// 16 = 0x10
    NSMutableDictionary *_pkgRefsByIdentifier;	// 24 = 0x18
    NSMutableArray *_pkgRefsInOrder;	// 32 = 0x20
    NSMutableDictionary *_stringsDictionaryByLocalization;	// 40 = 0x28
}

+ (id)_element:(id)arg1 coalescedAttributesDictionaryWithChildrenNamed:(id)arg2;	// IMP=0x000000000003131b
+ (id)maxSupportedSpecVersion;	// IMP=0x0000000000030c94
+ (BOOL)supportsSecureCoding;	// IMP=0x00000000000308a1
- (id)localizedStringForKey:(id)arg1 value:(id)arg2;	// IMP=0x0000000000038f2d
- (void)setStringsDictionary:(id)arg1 forLocalization:(id)arg2;	// IMP=0x0000000000038e38
- (id)stringsDictionaryForLocalization:(id)arg1;	// IMP=0x0000000000038cec
- (id)_stringsElementForLocalization:(id)arg1;	// IMP=0x0000000000038af7
- (id)localizations;	// IMP=0x000000000003891d
- (id)searchAttributesForIdentifier:(id)arg1;	// IMP=0x0000000000038610
- (id)_searchAttributeDictionaryForSearchElement:(id)arg1;	// IMP=0x0000000000038398
- (id)orderedSearchIdentifiers;	// IMP=0x00000000000380d0
- (void)setEnabledValue:(id)arg1 forDomain:(int)arg2;	// IMP=0x0000000000037fc6
- (id)enabledScriptForDomain:(int)arg1 creatingIfNeeded:(BOOL)arg2;	// IMP=0x0000000000037ddf
- (id)enabledValueForDomain:(int)arg1;	// IMP=0x0000000000037d3d
- (id)_attributeNameForDomain:(int)arg1;	// IMP=0x0000000000037d0c
- (id)_choicesUsingPackageReference:(id)arg1;	// IMP=0x0000000000037a94
- (id)allPackageIdentifiers;	// IMP=0x0000000000037928
- (id)packageReferenceForIdentifier:(id)arg1;	// IMP=0x00000000000378f1
- (void)removeObjectFromPackageReferencesAtIndex:(unsigned long long)arg1;	// IMP=0x0000000000037794
- (void)insertObject:(id)arg1 inPackageReferencesAtIndex:(unsigned long long)arg2;	// IMP=0x0000000000037225
- (id)objectInPackageReferencesAtIndex:(unsigned long long)arg1;	// IMP=0x00000000000371f4
- (unsigned long long)countOfPackageReferences;	// IMP=0x00000000000371c9
- (void)_didChangePkgRef:(id)arg1 originalIdentifier:(id)arg2 insertIndex:(unsigned long long)arg3;	// IMP=0x0000000000036f50
- (id)_pkgRefsInOrder;	// IMP=0x0000000000036da3
- (id)_pkgRefsByIdentifier;	// IMP=0x00000000000368e2
- (void)__cachePkgRefElement:(id)arg1;	// IMP=0x00000000000367e0
- (id)_futureSystemVersionDictionary;	// IMP=0x00000000000367a0
- (void)setRequiredBundleComponents:(id)arg1 requireAll:(BOOL)arg2 description:(id)arg3;	// IMP=0x0000000000036343
- (id)descriptionOfRequiredBundleComponents;	// IMP=0x00000000000362dd
- (BOOL)requireAllBundleComponents;	// IMP=0x0000000000036269
- (id)requiredBundleComponents;	// IMP=0x0000000000035f07
- (id)_minimumRequiredOSVersion;	// IMP=0x0000000000035d8a
- (void)setSupportedOSVersions:(id)arg1;	// IMP=0x0000000000035a90
- (id)supportedOSVersions;	// IMP=0x0000000000035823
- (id)peripheralCheckScriptCreatingIfNeeded:(BOOL)arg1;	// IMP=0x00000000000357d5
- (id)upgradeCheckScriptCreatingIfNeeded:(BOOL)arg1;	// IMP=0x0000000000035787
- (id)volumeCheckScriptCreatingIfNeeded:(BOOL)arg1;	// IMP=0x0000000000035739
- (void)setDescriptionOfRequiredHardwareProperties:(id)arg1;	// IMP=0x00000000000356ca
- (id)descriptionOfRequiredHardwareProperties;	// IMP=0x0000000000035664
- (void)setDescriptionOfRequiredGraphicsHardware:(id)arg1;	// IMP=0x00000000000355f5
- (id)descriptionOfRequiredGraphicsHardware;	// IMP=0x000000000003558f
- (void)setRequireSingleGraphicsDevice:(BOOL)arg1;	// IMP=0x0000000000035520
- (BOOL)requireSingleGraphicsDevice;	// IMP=0x00000000000354ba
- (void)setRequiredCLDevicePredicate:(id)arg1;	// IMP=0x00000000000354a1
- (id)requiredCLDevicePredicate;	// IMP=0x0000000000035488
- (void)setRequiredGLRendererPredicate:(id)arg1;	// IMP=0x000000000003546f
- (id)requiredGLRendererPredicate;	// IMP=0x0000000000035456
- (void)_setRequiredGraphicsPredicate:(id)arg1 ofType:(id)arg2;	// IMP=0x0000000000035309
- (id)_requiredGraphicsPredicateOfType:(id)arg1;	// IMP=0x00000000000351d6
- (void)setRequiredHardwarePropertiesPredicate:(id)arg1;	// IMP=0x000000000003507d
- (id)requiredHardwarePropertiesPredicate;	// IMP=0x0000000000034f45
- (void)setRequiredGigaBytesOfRAM:(id)arg1;	// IMP=0x0000000000034e14
- (id)requiredGigaBytesOfRAM;	// IMP=0x0000000000034d7d
- (id)installationCheckScriptCreatingIfNeeded:(BOOL)arg1;	// IMP=0x0000000000034d2f
- (id)peripheralCheckScript;	// IMP=0x0000000000034ced
- (id)upgradeCheckScript;	// IMP=0x0000000000034cab
- (id)volumeCheckScript;	// IMP=0x0000000000034c69
- (id)installationCheckScript;	// IMP=0x0000000000034c27
- (id)topScript;	// IMP=0x0000000000034bc9
- (id)_scriptUnder:(id)arg1 element:(id)arg2 attribute:(id)arg3 createIfNeeded:(BOOL)arg4;	// IMP=0x0000000000034aa8
- (void)setAuxInfoPropertyList:(id)arg1;	// IMP=0x00000000000348f4
- (id)auxInfoPropertyList;	// IMP=0x00000000000347b0
- (void)setTags:(id)arg1;	// IMP=0x0000000000034513
- (id)tags;	// IMP=0x0000000000034330
- (void)setOptionsDictionary:(id)arg1;	// IMP=0x00000000000342e8
- (id)optionsDictionary;	// IMP=0x0000000000034297
- (void)setIOMatchingDictionary:(id)arg1;	// IMP=0x00000000000341dd
- (id)ioMatchingDictionary;	// IMP=0x0000000000034173
- (void)_verifyAndRepairChoiceTreeWithReferencingElement:(id)arg1 movedOrSynthesizedChoices:(id *)arg2;	// IMP=0x0000000000033bf2
- (void)_findIncorrectlyNestedChoicesUnder:(id)arg1 addTo:(id)arg2;	// IMP=0x0000000000033a2f
- (void)_verifyAndRepairChoiceTreeForInterfaceType:(id)arg1;	// IMP=0x00000000000337bc
- (id)choiceForIdentifier:(id)arg1;	// IMP=0x0000000000033785
- (id)rootChoiceForInterfaceType:(id)arg1 creatingIfNeeded:(BOOL)arg2;	// IMP=0x000000000003371e
- (id)interfaceTypes;	// IMP=0x0000000000033580
- (id)_choicesOutlineElementForInterfaceType:(id)arg1 creatingIfNeeded:(BOOL)arg2;	// IMP=0x0000000000033348
- (void)_didChangeChoice:(id)arg1 originalIdentifier:(id)arg2;	// IMP=0x0000000000033152
- (id)_choicesByIdentifier;	// IMP=0x0000000000032da5
- (void)__cacheLineElements:(id)arg1;	// IMP=0x0000000000032b3b
- (void)setResourceAttributes:(id)arg1 forKey:(id)arg2;	// IMP=0x0000000000032ae9
- (id)resourceAttributesForKey:(id)arg1;	// IMP=0x0000000000032a9a
- (void)setResourceData:(id)arg1 forKey:(id)arg2;	// IMP=0x00000000000329be
- (id)resourceDataForKey:(id)arg1;	// IMP=0x0000000000032901
- (void)setVersionKey:(id)arg1;	// IMP=0x00000000000328b9
- (id)versionKey;	// IMP=0x0000000000032879
- (void)setTitleKey:(id)arg1;	// IMP=0x0000000000032831
- (id)titleKey;	// IMP=0x00000000000327f1
- (void)_setSystemImagePackageReferences:(id)arg1;	// IMP=0x00000000000324b5
- (void)_setSystemImageInformation:(id)arg1;	// IMP=0x0000000000031eeb
- (id)_systemImagePackageReferences;	// IMP=0x0000000000031bc7
- (id)_systemImageInformation;	// IMP=0x0000000000031963
- (void)setProductVersion:(id)arg1;	// IMP=0x00000000000318e3
- (void)setProductIdentifier:(id)arg1;	// IMP=0x0000000000031863
- (id)productVersion;	// IMP=0x0000000000031810
- (id)productIdentifier;	// IMP=0x00000000000317bd
- (id)objectForSourceURI:(id)arg1 returningAttributeName:(id *)arg2;	// IMP=0x0000000000031578
- (void)setPlatformAttributes:(id)arg1 forType:(id)arg2;	// IMP=0x0000000000031512
- (id)platformAttributesForType:(id)arg1;	// IMP=0x00000000000314b7
- (id)_rootElement;	// IMP=0x000000000003149a
- (void)setMinSpecVersion:(id)arg1;	// IMP=0x00000000000312ca
- (id)minSpecVersion;	// IMP=0x00000000000312b6
- (id)_minSpecVersionAddingSupportedOSVersionIfNeeded:(BOOL)arg1;	// IMP=0x0000000000030e2f
- (double)_currentMinSpecVersionReturningSupportedOSVersion:(id *)arg1;	// IMP=0x0000000000030cb5
- (void)_setDistributionURL:(id)arg1;	// IMP=0x0000000000030c58
- (id)XMLData;	// IMP=0x0000000000030b43
- (id)distributionURL;	// IMP=0x0000000000030b01
- (void)dealloc;	// IMP=0x0000000000030a47
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000000000309c5
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000000030954
- (id)initWithCoder:(id)arg1;	// IMP=0x00000000000308ac
- (id)initWithData:(id)arg1 error:(id *)arg2;	// IMP=0x00000000000307da
- (id)initWithContentsOfURL:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000030713
- (id)init;	// IMP=0x0000000000030681
- (id)_initWithXMLDocument:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000030282

@end

