//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PKPackageReferable.h"

@class NSMutableArray, NSString, PKDistribution;

@interface PKDistributionPackageReference : NSObject <PKPackageReferable>
{
    NSMutableArray *_pkgRefElements;	// 8 = 0x8
    NSString *_pkgRefIdentifier;	// 16 = 0x10
    PKDistribution *_distribution;	// 24 = 0x18
}

- (id)_distValueFromExternalValue:(id)arg1 forExternalName:(id)arg2;	// IMP=0x00000000000528d9
- (id)_externalValueFromDistValue:(id)arg1 forExternalName:(id)arg2;	// IMP=0x000000000005270c
- (id)_distNameFromExternalName:(id)arg1;	// IMP=0x0000000000052655
- (id)componentIdentifierToSearchIdentifierMap;	// IMP=0x000000000005221e
- (id)objectInMustCloseAppsAtIndex:(unsigned long long)arg1;	// IMP=0x000000000005211f
- (unsigned long long)countOfMustCloseApps;	// IMP=0x0000000000052072
- (void)setBundleComponents:(id)arg1;	// IMP=0x0000000000051d61
- (id)bundleComponents;	// IMP=0x0000000000051a70
- (id)_bundleVersionElementCreatingIfNeeded:(BOOL)arg1;	// IMP=0x000000000005198e
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;	// IMP=0x000000000005197c
- (id)valueForUndefinedKey:(id)arg1;	// IMP=0x000000000005196a
- (id)attributesAsDictionary;	// IMP=0x0000000000051758
- (id)scriptForAttributeName:(id)arg1 createIfNeeded:(BOOL)arg2;	// IMP=0x0000000000051493
- (id)scriptForAttributeName:(id)arg1;	// IMP=0x000000000005147f
- (void)setValue:(id)arg1 forAttributeName:(id)arg2;	// IMP=0x00000000000511c1
- (id)valueForAttributeName:(id)arg1;	// IMP=0x0000000000051091
- (id)_pkgRefElementForWriting:(BOOL)arg1 passingBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000000050d9a
- (void)setURL:(id)arg1;	// IMP=0x0000000000050c6a
- (void)setPackageIdentifier:(id)arg1;	// IMP=0x0000000000050bb3
- (id)packageIdentifier;	// IMP=0x0000000000050b9a
- (BOOL)validatePkgRefIdentifier:(id *)arg1 error:(id *)arg2;	// IMP=0x00000000000509c2
- (void)setPkgRefIdentifier:(id)arg1;	// IMP=0x00000000000507ed
- (id)pkgRefIdentifier;	// IMP=0x00000000000507dc
- (id)URL;	// IMP=0x0000000000050652
- (id)version;	// IMP=0x0000000000050639
- (id)identifier;	// IMP=0x0000000000050605
- (void)_replacePkgRefIdentifier:(id)arg1;	// IMP=0x000000000005053a
- (id)_pkgRefElements;	// IMP=0x0000000000050529
- (void)_removePkgRefElement:(id)arg1;	// IMP=0x000000000005050c
- (void)_addPkgRefElement:(id)arg1;	// IMP=0x00000000000503e8
- (void)_setDistribution:(id)arg1;	// IMP=0x00000000000503d7
- (id)distribution;	// IMP=0x00000000000503c6
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;	// IMP=0x0000000000050358
- (void)dealloc;	// IMP=0x00000000000502d1
- (id)_initWithDistribution:(id)arg1 pkgRefIdentifier:(id)arg2;	// IMP=0x0000000000050206
- (id)init;	// IMP=0x00000000000501f0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

