//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSXMLElement, NSXMLNode;

@interface PKDistributionScript : NSObject
{
    NSXMLNode *_node;	// 8 = 0x8
    NSXMLElement *_addToParent;	// 16 = 0x10
    BOOL _useParentAsScriptParent;	// 24 = 0x18
}

- (void)remove;	// IMP=0x000000000004d75d
- (id)literalValue;	// IMP=0x000000000004d694
- (id)sourceTextForEvaluation;	// IMP=0x000000000004d5e5
- (void)setScript:(id)arg1;	// IMP=0x000000000004d1f5
- (void)setValue:(id)arg1;	// IMP=0x000000000004d156
- (id)sourceURI;	// IMP=0x000000000004d071
- (void)_addToParentIfNeeded;	// IMP=0x000000000004cfb1
- (id)attributeName;	// IMP=0x000000000004cf6d
- (id)script;	// IMP=0x000000000004cbe6
- (id)_scriptParent;	// IMP=0x000000000004cad0
- (id)_forIdentifier;	// IMP=0x000000000004c972
- (id)value;	// IMP=0x000000000004c92f
- (void)_setUseParentAsScriptParent:(BOOL)arg1;	// IMP=0x000000000004c91f
- (id)description;	// IMP=0x000000000004c7f2
- (void)dealloc;	// IMP=0x000000000004c76b
- (id)_initWithExpression:(id)arg1;	// IMP=0x000000000004c726
- (id)_initWithNode:(id)arg1 addToParent:(id)arg2;	// IMP=0x000000000004c655
- (id)_initWithNode:(id)arg1;	// IMP=0x000000000004c641

@end

