//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@interface PKDownloaderSpeedTracker : NSObject
{
    unsigned long long _averageBytesPerSecond;	// 8 = 0x8
    NSDate *_queueStartTime;	// 16 = 0x10
    unsigned long long _bytesSinceQueueStart;	// 24 = 0x18
    unsigned long long _bytesAtLastUpdate;	// 32 = 0x20
}

- (void)updateSpeed;	// IMP=0x000000000003bb58
- (void)didGetBytes:(unsigned long long)arg1;	// IMP=0x000000000003bb47
- (void)setAverageBytesPerSecond:(unsigned long long)arg1;	// IMP=0x000000000003bb36
- (unsigned long long)averageBytesPerSecond;	// IMP=0x000000000003bb25
- (id)description;	// IMP=0x000000000003bab7
- (void)dealloc;	// IMP=0x000000000003ba50
- (id)init;	// IMP=0x000000000003b9c2

@end

