//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PKDownload : NSObject
{
    NSString *_dstPath;	// 8 = 0x8
    BOOL _deleteFileOnFailure;	// 16 = 0x10
    BOOL _overwriteIfFileExists;	// 17 = 0x11
    id <PKDownloadDelegate><NSObject> _delegate;	// 24 = 0x18
}

+ (id)downloadWithResumeData:(id)arg1 destination:(id)arg2 delegate:(id)arg3;	// IMP=0x0000000000064298
+ (id)downloadWithURL:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000000064116
+ (BOOL)canDownloadWithResumeData:(id)arg1;	// IMP=0x000000000006407e
+ (BOOL)canDownloadURL:(id)arg1;	// IMP=0x0000000000064076
+ (void)addDownloadClass:(Class)arg1;	// IMP=0x0000000000064045
+ (id)_downloadClasses;	// IMP=0x0000000000063fc7
- (BOOL)validatesDuringDownload;	// IMP=0x00000000000645b3
- (void)setDestination:(id)arg1 allowOverwrite:(BOOL)arg2;	// IMP=0x0000000000064555
- (BOOL)deletesFileUponFailure;	// IMP=0x0000000000064544
- (void)setDeletesFileUponFailure:(BOOL)arg1;	// IMP=0x0000000000064534
- (id)resumeData;	// IMP=0x00000000000644f1
- (id)sourceURL;	// IMP=0x00000000000644ae
- (id)sourcePath;	// IMP=0x000000000006446b
- (void)cancel;	// IMP=0x0000000000064428
- (id)initWithResumeData:(id)arg1 destination:(id)arg2 delegate:(id)arg3;	// IMP=0x00000000000640ce
- (id)initWithURL:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000000064086

@end

