//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, PKDownload, PKPackageReference;

@interface PKDownloaderQueueElement : NSObject
{
    PKPackageReference *_packageRef;	// 8 = 0x8
    NSString *_destination;	// 16 = 0x10
    PKDownload *_download;	// 24 = 0x18
    unsigned long long _downloadedBytes;	// 32 = 0x20
    unsigned long long _checksummedBytes;	// 40 = 0x28
    unsigned long long _progressIncrement;	// 48 = 0x30
}

- (unsigned long long)_getAndClearProgressIncrement;	// IMP=0x000000000003c1fc
- (unsigned long long)_reportedProgress;	// IMP=0x000000000003c13b
- (void)_addToChecksummedBytes:(unsigned long long)arg1;	// IMP=0x000000000003c09a
- (unsigned long long)checksummedBytes;	// IMP=0x000000000003c070
- (void)_addToDownloadedBytes:(unsigned long long)arg1;	// IMP=0x000000000003bfcf
- (unsigned long long)downloadedBytes;	// IMP=0x000000000003bfa5
- (void)_resetProgress;	// IMP=0x000000000003bf5c
- (void)setDownload:(id)arg1;	// IMP=0x000000000003bf10
- (id)download;	// IMP=0x000000000003beff
- (id)resumeDataPath;	// IMP=0x000000000003bedb
- (id)partialPath;	// IMP=0x000000000003beb7
- (id)destination;	// IMP=0x000000000003bea6
- (id)packageReference;	// IMP=0x000000000003be95
- (id)description;	// IMP=0x000000000003bd89
- (void)dealloc;	// IMP=0x000000000003bcf1
- (id)initWithPackageReference:(id)arg1 destination:(id)arg2;	// IMP=0x000000000003bc48

@end

