//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface PKDownloaderQueue : NSObject
{
    unsigned long long _maxConcurrentDownloadCount;	// 8 = 0x8
    NSMutableArray *_queue;	// 16 = 0x10
    NSMutableDictionary *_active;	// 24 = 0x18
    unsigned long long _totalSizeQueued;	// 32 = 0x20
    unsigned long long _sizeDequeued;	// 40 = 0x28
    unsigned long long _sizeDownloaded;	// 48 = 0x30
    unsigned long long _sizeToDownload;	// 56 = 0x38
    unsigned long long _sizeToCheck;	// 64 = 0x40
    unsigned long long _dequeuedProgressIncrement;	// 72 = 0x48
    double _progressDerating;	// 80 = 0x50
    double _progressPercentage;	// 88 = 0x58
}

- (void)_adjustQueueSizeBy:(long long)arg1;	// IMP=0x000000000003cf70
- (void)updateProgressInfo;	// IMP=0x000000000003cc15
- (void)checkedDataOfLength:(unsigned long long)arg1 forElement:(id)arg2;	// IMP=0x000000000003cc00
- (void)gotDataOfLength:(unsigned long long)arg1 forElement:(id)arg2;	// IMP=0x000000000003cbeb
- (void)clearAll;	// IMP=0x000000000003cb3d
- (void)deactivateElement:(id)arg1;	// IMP=0x000000000003ca90
- (void)revertElement:(id)arg1 keepActive:(BOOL)arg2;	// IMP=0x000000000003ca05
- (void)removeElement:(id)arg1 didFinish:(BOOL)arg2;	// IMP=0x000000000003c890
- (void)addElement:(id)arg1;	// IMP=0x000000000003c821
- (double)progressPercentage;	// IMP=0x000000000003c80f
- (unsigned long long)sizeToCheck;	// IMP=0x000000000003c7fe
- (unsigned long long)sizeToDownload;	// IMP=0x000000000003c7ed
- (unsigned long long)sizeDownloaded;	// IMP=0x000000000003c7dc
- (unsigned long long)totalSizeQueued;	// IMP=0x000000000003c7cb
- (id)activeElementForURL:(id)arg1;	// IMP=0x000000000003c78f
- (id)activateNextElement;	// IMP=0x000000000003c6b2
- (id)allElements;	// IMP=0x000000000003c66e
- (id)activeElements;	// IMP=0x000000000003c651
- (BOOL)isEmpty;	// IMP=0x000000000003c601
- (void)setMaxConcurrentDownloadCount:(long long)arg1;	// IMP=0x000000000003c5f0
- (long long)maxConcurrentDownloadCount;	// IMP=0x000000000003c5df
- (id)description;	// IMP=0x000000000003c3a9
- (void)dealloc;	// IMP=0x000000000003c322
- (id)init;	// IMP=0x000000000003c22e

@end

