//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer, PKDownloaderQueue, PKDownloaderSpeedTracker;

@interface PKDownloader : NSObject
{
    id _delegate;	// 8 = 0x8
    PKDownloaderQueue *_queue;	// 16 = 0x10
    BOOL _isQueueRunning;	// 24 = 0x18
    BOOL _stopNotificationPending;	// 25 = 0x19
    PKDownloaderSpeedTracker *_downloadTracker;	// 32 = 0x20
    PKDownloaderSpeedTracker *_checksumTracker;	// 40 = 0x28
    NSTimer *_progressTimer;	// 48 = 0x30
}

+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;	// IMP=0x0000000000039164
+ (id)keyPathsForValuesAffectingEstimatedTimeRemaining;	// IMP=0x0000000000039110
+ (void)setUserAgent:(id)arg1;	// IMP=0x00000000000390d0
+ (id)userAgent;	// IMP=0x00000000000390c3
- (BOOL)_wantHTTPLogging;	// IMP=0x000000000003b422
- (void)_element:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x000000000003b286
- (void)_elementDidFinish:(id)arg1;	// IMP=0x000000000003b148
- (void)_updateDownloadSpeed;	// IMP=0x000000000003b0e3
- (void)_updateProgressInfo;	// IMP=0x000000000003afe6
- (void)_updateIndicators:(id)arg1;	// IMP=0x000000000003afb8
- (void)_notifyDelegateIfQueueStopped:(id)arg1;	// IMP=0x000000000003af08
- (BOOL)_cancelDownloadCapturingResumeData:(id)arg1;	// IMP=0x000000000003adfd
- (void)_postProcessDownloadWithArgs:(id)arg1;	// IMP=0x000000000003ab6e
- (BOOL)_validatePackageAtPath:(id)arg1;	// IMP=0x000000000003aae8
- (void)_startNativeValidationForDownload:(id)arg1;	// IMP=0x000000000003a80f
- (void)_startChecksumValidationForDownload:(id)arg1;	// IMP=0x000000000003a469
- (void)_finishFileCopyWithResult:(id)arg1;	// IMP=0x000000000003a345
- (void)_startFileCopyForQueueElement:(id)arg1;	// IMP=0x000000000003a073
- (void)_startDownloadForQueueElement:(id)arg1;	// IMP=0x0000000000039de1
- (void)_startQueuedDownloads;	// IMP=0x0000000000039d0f
- (void)_stopUpdateTimer;	// IMP=0x0000000000039cc5
- (void)_startUpdateTimer;	// IMP=0x0000000000039c6b
- (void)setIsQueueRunning:(BOOL)arg1;	// IMP=0x0000000000039c5b
- (double)estimatedTimeRemaining;	// IMP=0x0000000000039b43
- (unsigned long long)totalDownloadSize;	// IMP=0x0000000000039b26
- (unsigned long long)completedDownloadSize;	// IMP=0x0000000000039b09
- (double)progressValue;	// IMP=0x0000000000039aec
- (BOOL)isQueueEmpty;	// IMP=0x0000000000039acf
- (BOOL)isQueueRunning;	// IMP=0x0000000000039abe
- (void)cancelDownloadWithPackageReference:(id)arg1;	// IMP=0x0000000000039902
- (void)clearQueue;	// IMP=0x00000000000398cc
- (void)stopQueue;	// IMP=0x0000000000039735
- (void)startQueue;	// IMP=0x00000000000395bb
- (BOOL)queueContainsPackageReference:(id)arg1;	// IMP=0x0000000000039525
- (void)queuePackageReference:(id)arg1 destination:(id)arg2;	// IMP=0x000000000003947d
- (void)setMaxConcurrentDownloadCount:(long long)arg1;	// IMP=0x0000000000039460
- (long long)maxConcurrentDownloadCount;	// IMP=0x0000000000039443
- (id)description;	// IMP=0x000000000003936d
- (void)dealloc;	// IMP=0x00000000000392b2
- (id)initWithDelegate:(id)arg1;	// IMP=0x0000000000039215
- (void)download:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x000000000003b949
- (void)downloadDidFinish:(id)arg1;	// IMP=0x000000000003b8e0
- (void)download:(id)arg1 didCheckDataOfLength:(unsigned long long)arg2;	// IMP=0x000000000003b861
- (void)download:(id)arg1 didReceiveDataOfLength:(unsigned long long)arg2;	// IMP=0x000000000003b7e2
- (void)download:(id)arg1 didReceiveResponse:(id)arg2;	// IMP=0x000000000003b702
- (void)download:(id)arg1 willResumeFromByte:(long long)arg2;	// IMP=0x000000000003b620
- (id)download:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;	// IMP=0x000000000003b52b
- (void)download:(id)arg1 didCancelAuthenticationChallenge:(id)arg2;	// IMP=0x000000000003b4d0
- (void)download:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;	// IMP=0x000000000003b475

@end

