//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface PKExtendedAttribute : NSObject
{
    NSString *_name;	// 8 = 0x8
    NSData *_value;	// 16 = 0x10
}

@property(copy) NSData *value; // @synthesize value=_value;
@property(copy) NSString *name; // @synthesize name=_name;
- (BOOL)setOnFileAtPath:(id)arg1 option:(int)arg2;	// IMP=0x000000000006148f
- (id)description;	// IMP=0x0000000000061454
- (void)dealloc;	// IMP=0x00000000000613cd
- (id)initWithName:(id)arg1 value:(id)arg2;	// IMP=0x0000000000061310

@end

