//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PKExtendedAttributeEnumerator : NSObject
{
    NSString *_path;	// 8 = 0x8
    char *_nameBuffer;	// 16 = 0x10
    long long _nameBufferSize;	// 24 = 0x18
    char *_currentName;	// 32 = 0x20
    long long _currentByteOffset;	// 40 = 0x28
    int _options;	// 48 = 0x30
}

- (id)_dataForAttributeName:(char *)arg1;	// IMP=0x000000000000b4be
- (void)rewindToBeginning;	// IMP=0x000000000000b49a
- (id)nextAttribute;	// IMP=0x000000000000b3b3
- (void)dealloc;	// IMP=0x000000000000b337
- (id)initWithFileAtPath:(id)arg1 options:(int)arg2;	// IMP=0x000000000000b209

@end

