//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@class NSObject<OS_dispatch_queue>, PKPackageSpecifier, PKPayloadCopier;

@interface PKExtractInstallOperation : PKInstallOperation
{
    unsigned long long _payloadBytesCompleted;	// 80 = 0x50
    unsigned long long _totalPayloadSize;	// 88 = 0x58
    unsigned long long _informedExtractionSpeed;	// 96 = 0x60
    PKPackageSpecifier *_currentPackageSpecifier;	// 104 = 0x68
    PKPayloadCopier *_activeExtractor;	// 112 = 0x70
    NSObject<OS_dispatch_queue> *_updateQueue;	// 120 = 0x78
}

- (void)cancel;	// IMP=0x000000000005c3e4
- (void)main;	// IMP=0x000000000005c060
- (BOOL)_extractPayloadForPackageSpecifier:(id)arg1 error:(id *)arg2;	// IMP=0x000000000005bb47
- (BOOL)_extractScriptsForPackageSpecifier:(id)arg1 error:(id *)arg2;	// IMP=0x000000000005b917
- (BOOL)_extractBomForPackageSpecifier:(id)arg1 error:(id *)arg2;	// IMP=0x000000000005b7cd
- (id)_activeExtractor;	// IMP=0x000000000005b604
- (void)_setActiveExtractor:(id)arg1;	// IMP=0x000000000005b4d6
- (id)messageTracerComment;	// IMP=0x000000000005b481
- (id)messageTracerDomain;	// IMP=0x000000000005b474
- (id)currentPackageSpecifier;	// IMP=0x000000000005b463
- (int)installState;	// IMP=0x000000000005b458
- (double)estimatedTimeRemaining;	// IMP=0x000000000005b3b0
- (void)dealloc;	// IMP=0x000000000005b351
- (id)initWithRequest:(id)arg1 sandbox:(id)arg2 analyzer:(id)arg3;	// IMP=0x000000000005b044

@end

