//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, PKBundleComponent, PKBundleComponentVersion;

@interface PKFirmwareBundleComponent : NSObject
{
    long long _type;	// 8 = 0x8
    NSArray *_variants;	// 16 = 0x10
    NSArray *_models;	// 24 = 0x18
    PKBundleComponent *_bundle;	// 32 = 0x20
}

+ (long long)typeForString:(id)arg1;	// IMP=0x000000000006be59
@property(retain) PKBundleComponent *bundle; // @synthesize bundle=_bundle;
@property(retain) NSArray *models; // @synthesize models=_models;
@property(retain) NSArray *variants; // @synthesize variants=_variants;
@property long long type; // @synthesize type=_type;
@property(readonly) PKBundleComponentVersion *bundleComponentVersion;
@property(readonly) NSString *bundlePath;
- (void)dealloc;	// IMP=0x000000000006bd6b

@end

