//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKDownload.h>

@class NSString, NSThread;

@interface PKFileDownload : PKDownload
{
    NSString *_srcPath;	// 32 = 0x20
    int _readFileDescriptor;	// 40 = 0x28
    int _writeFileDescriptor;	// 44 = 0x2c
    long long _bytesDownloaded;	// 48 = 0x30
    BOOL _isResume;	// 56 = 0x38
    BOOL _runFileReadThread;	// 57 = 0x39
    NSThread *_fileReadThread;	// 64 = 0x40
}

+ (BOOL)canDownloadWithResumeData:(id)arg1;	// IMP=0x00000000000645d0
+ (BOOL)canDownloadURL:(id)arg1;	// IMP=0x00000000000645bb
- (void)_currentThreadCallback:(id)arg1;	// IMP=0x00000000000654d5
- (int)_fileCopyThread:(id)arg1;	// IMP=0x0000000000064d8e
- (void)setDestination:(id)arg1 allowOverwrite:(BOOL)arg2;	// IMP=0x0000000000064c7f
- (id)resumeData;	// IMP=0x0000000000064ba1
- (id)sourceURL;	// IMP=0x0000000000064b7a
- (id)sourcePath;	// IMP=0x0000000000064b44
- (void)cancel;	// IMP=0x0000000000064a5a
- (void)dealloc;	// IMP=0x0000000000064999
- (id)initWithResumeData:(id)arg1 destination:(id)arg2 delegate:(id)arg3;	// IMP=0x00000000000646e5
- (id)initWithURL:(id)arg1 delegate:(id)arg2;	// IMP=0x000000000006462a

@end

