//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PKFirmwareBundleComponentModel : NSObject
{
    NSString *_modelID;	// 8 = 0x8
    unsigned int _boardID;	// 16 = 0x10
    unsigned int _chipID;	// 20 = 0x14
}

+ (id)modelWithBoardID:(unsigned int)arg1 chipID:(unsigned int)arg2;	// IMP=0x000000000006bc94
@property unsigned int chipID; // @synthesize chipID=_chipID;
@property unsigned int boardID; // @synthesize boardID=_boardID;
@property(retain) NSString *modelID; // @synthesize modelID=_modelID;

@end

