//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface PKFirmwareInstallationController : NSObject
{
    NSArray *_firmwareComponents;	// 8 = 0x8
    NSString *_sandboxPath;	// 16 = 0x10
}

@property(retain) NSString *sandboxPath; // @synthesize sandboxPath=_sandboxPath;
@property(retain) NSArray *firmwareComponents; // @synthesize firmwareComponents=_firmwareComponents;
- (void)installWithProgressHandler:(CDUnknownBlockType)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000000045e6a
- (BOOL)shouldInstallReturningError:(id *)arg1;	// IMP=0x0000000000045e39
- (id)firmwareComponentsOfType:(long long)arg1;	// IMP=0x0000000000045cc0
- (void)dealloc;	// IMP=0x0000000000045c39
- (id)initWithFirmwareComponents:(id)arg1 sandboxPath:(id)arg2;	// IMP=0x0000000000045b90

@end

