//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKMutableDistributionContainer.h>

@class NSString;

@interface PKFlatDistributionContainer : PKMutableDistributionContainer
{
    NSString *_path;	// 24 = 0x18
}

- (BOOL)commitReturningError:(id *)arg1;	// IMP=0x0000000000057080
- (BOOL)setResourceData:(id)arg1 forKey:(id)arg2 forLocalization:(id)arg3;	// IMP=0x0000000000056e75
- (BOOL)setStringsData:(id)arg1 forLocalization:(id)arg2;	// IMP=0x0000000000056d78
- (BOOL)setDistributionFromContainer:(id)arg1;	// IMP=0x0000000000056cca
- (id)_resourceDataForKey:(id)arg1;	// IMP=0x0000000000056b97
- (id)localizedStringForKey:(id)arg1 value:(id)arg2;	// IMP=0x0000000000056b57
- (id)stringsDictionary;	// IMP=0x00000000000569e4
- (void)dealloc;	// IMP=0x000000000005697d
- (id)initWithPath:(id)arg1 forWriting:(BOOL)arg2 error:(id *)arg3;	// IMP=0x0000000000056897

@end

