//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKProduct.h>

@class PKArchive, PKDistribution;

@interface PKFolderArchiveProduct : PKProduct
{
    PKArchive *_archive;	// 40 = 0x28
    PKDistribution *_distribution;	// 48 = 0x30
}

+ (BOOL)canInitWithURL:(id)arg1;	// IMP=0x0000000000086fe9
- (id)_synthesizedDistributionFromMetaPackageInArchive:(id)arg1;	// IMP=0x0000000000086bbb
- (id)_distributionDataFromArchive:(id)arg1 returningDistributionURL:(id *)arg2 error:(id *)arg3;	// IMP=0x0000000000086953
- (id)allPackageReferences;	// IMP=0x00000000000866be
- (id)localizedStringForKey:(id)arg1 value:(id)arg2;	// IMP=0x00000000000866b6
- (id)stringsDictionary;	// IMP=0x00000000000866ae
- (id)distributionContainer;	// IMP=0x00000000000866a6
- (id)distribution;	// IMP=0x0000000000086695
- (id)productType;	// IMP=0x0000000000086685
- (id)URL;	// IMP=0x0000000000086645
- (void)dealloc;	// IMP=0x00000000000865be
- (id)_initWithPath:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000086425
- (BOOL)evaluateTrustReturningError:(id *)arg1;	// IMP=0x0000000000087177
- (id)_archiveForTrustEvaluation;	// IMP=0x0000000000087166
- (id)initByLoadingProductAtURL:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000087123

@end

