//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKArchiveSignature.h>

@interface PKFolderArchiveSignature : PKArchiveSignature
{
    struct __SecCode *_staticCode;	// 16 = 0x10
}

- (BOOL)verifySignedDataReturningError:(id *)arg1;	// IMP=0x000000000000ca80
- (BOOL)verifyCodeSignatureIncludingSealedResources:(BOOL)arg1 error:(id *)arg2;	// IMP=0x000000000000c92a
- (id)signatureDataReturningAlgorithm:(id *)arg1;	// IMP=0x000000000000c922
- (id)signedDataReturningAlgorithm:(id *)arg1;	// IMP=0x000000000000c91a
- (id)algorithmType;	// IMP=0x000000000000c90a
- (id)certificateRefs;	// IMP=0x000000000000c86c
- (void)dealloc;	// IMP=0x000000000000c808
- (id)initWithArchiveAtPath:(id)arg1;	// IMP=0x000000000000c708

@end

