//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PKInstallService.h"
#import "PKInstallServiceClient.h"

@class NSMutableSet, NSObject<OS_dispatch_queue>, NSString, NSXPCConnection;

@interface PKInstallDaemonClient : NSObject <PKInstallService, PKInstallServiceClient>
{
    NSXPCConnection *_connection;	// 8 = 0x8
    int _clientPID;	// 16 = 0x10
    int _clientAuditIdentifier;	// 20 = 0x14
    unsigned int _clientUID;	// 24 = 0x18
    NSString *_clientPath;	// 32 = 0x20
    NSMutableSet *_outstandingInstallTokens;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_clientQueue;	// 48 = 0x30
}

@property(readonly, retain) NSXPCConnection *connection; // @synthesize connection=_connection;
- (void)installDidEndForToken:(id)arg1;	// IMP=0x0000000000088edc
- (void)installDidBeginCommitForToken:(id)arg1;	// IMP=0x0000000000088ea0
- (void)installDidBeginForToken:(id)arg1;	// IMP=0x0000000000088e64
- (void)purgeOrphanedSandboxesOnVolume:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000000088e1d
- (void)purgeableSpaceForOrphanedSandboxesOnVolume:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000000088dd6
- (void)startPurgeOfSandboxesOnVolume:(id)arg1 purgeAmountNeeded:(unsigned long long)arg2 systemSandboxes:(BOOL)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x0000000000088d7b
- (void)estimateOfPurgeableSpaceForSandboxesOnVolume:(id)arg1 systemSandboxes:(BOOL)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0000000000088d2f
- (void)currentStageStatusOfInstallRequest:(id)arg1 calculatePurgeableSize:(BOOL)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0000000000088ce3
- (void)registerAuthorizationFromInstallRequest:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000000088c9c
- (void)adoptToken:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000000088c55
- (void)tokenForCurrentCommitIgnoringBlockingClients:(BOOL)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000000088a2d
- (void)displayNamesForToken:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00000000000889e6
- (void)installStatusForToken:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000000008899f
- (void)addToken:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000000088958
- (void)tokenForInstallRequest:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000000088725
- (void)invalidate;	// IMP=0x000000000008868a
- (void)cancelInstallsWherePossible;	// IMP=0x000000000008849d
- (BOOL)isWatchingInstallWithToken:(id)arg1;	// IMP=0x0000000000088315
@property(readonly, copy) NSString *description;
- (void)dealloc;	// IMP=0x00000000000881d3
- (id)initWithConnection:(id)arg1;	// IMP=0x0000000000087fbd

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

