//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PKInstallError : NSObject
{
}

+ (id)errorWithCode:(long long)arg1 underlyingError:(id)arg2;	// IMP=0x0000000000013a2d
+ (id)errorWithCode:(long long)arg1 userInfo:(id)arg2;	// IMP=0x0000000000013a13
+ (id)errorWithCode:(long long)arg1 package:(id)arg2 userInfo:(id)arg3;	// IMP=0x0000000000013862
+ (id)localizedDescriptionForCode:(long long)arg1;	// IMP=0x00000000000137cf

@end

