//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSError, NSObject<OS_dispatch_queue>, NSSet, PKInstallAnalyzer, PKInstallOperationController, PKInstallRequest, PKInstallSandbox;

@interface PKInstall : NSObject
{
    PKInstallRequest *_installRequest;	// 8 = 0x8
    id _delegate;	// 16 = 0x10
    PKInstallSandbox *_installSandbox;	// 24 = 0x18
    PKInstallAnalyzer *_installAnalyzer;	// 32 = 0x20
    PKInstallOperationController *_installController;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_installControllerUpdateQueue;	// 48 = 0x30
    BOOL _isDone;	// 56 = 0x38
    BOOL _isCancelled;	// 57 = 0x39
    NSError *_error;	// 64 = 0x40
    int _installState;	// 72 = 0x48
    NSArray *_clientSideRegistrationPaths;	// 80 = 0x50
    NSSet *_previousPackageIdentifiersSharingGroupsWithCurrentRequest;	// 88 = 0x58
}

- (id)_previousPackageIdentifiersSharingGroupsWithCurrentRequest;	// IMP=0x00000000000111b3
- (void)_handleCanCancelDidChange:(id)arg1;	// IMP=0x00000000000110fa
- (void)_releaseResources;	// IMP=0x0000000000010f41
- (void)_setInstallController:(id)arg1;	// IMP=0x0000000000010e13
- (id)_installController;	// IMP=0x0000000000010c4a
- (void)_installMain:(id)arg1;	// IMP=0x000000000000fd91
- (id)registrationPaths;	// IMP=0x000000000000fd5b
- (id)request;	// IMP=0x000000000000fd4a
- (id)error;	// IMP=0x000000000000fd39
- (id)_currentPackageSpecifier;	// IMP=0x000000000000fd0e
- (int)installState;	// IMP=0x000000000000fccc
- (double)progressValue;	// IMP=0x000000000000fc1c
- (double)estimatedTimeRemaining;	// IMP=0x000000000000fbeb
- (BOOL)isDone;	// IMP=0x000000000000fbda
- (BOOL)canCancel;	// IMP=0x000000000000fbab
- (BOOL)cancel;	// IMP=0x000000000000fb5d
- (void)start;	// IMP=0x000000000000fb3b
- (void)_startWithQualityOfServiceClass:(unsigned int)arg1;	// IMP=0x000000000000fa2a
- (void)dealloc;	// IMP=0x000000000000f918
- (id)initWithRequest:(id)arg1 delegate:(id)arg2 error:(id *)arg3;	// IMP=0x000000000000f865

@end

