//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSArray, NSData, NSDictionary, NSFileHandle, NSMachPort, NSString;

@interface PKInstallRequest : NSObject <NSSecureCoding>
{
    NSArray *_packageSpecifiers;	// 8 = 0x8
    NSString *_destinationPath;	// 16 = 0x10
    long long _installPhases;	// 24 = 0x18
    BOOL _useForegroundPriorityForStaging;	// 32 = 0x20
    double _frameworkVersion;	// 40 = 0x28
    NSString *_clientProcessName;	// 48 = 0x30
    BOOL _openScripts;	// 56 = 0x38
    BOOL _internalBundleVersionChecking;	// 57 = 0x39
    NSString *_scriptTargetVolume;	// 64 = 0x40
    NSString *_loggingIdentifier;	// 72 = 0x48
    BOOL _ignoreIndexBom;	// 80 = 0x50
    BOOL _useAFSCByDefault;	// 81 = 0x51
    BOOL _isRecursive;	// 82 = 0x52
    NSData *_appStoreReceiptData;	// 88 = 0x58
    unsigned long long _spaceRequiredForInstall;	// 96 = 0x60
    BOOL _clientBlocksRestart;	// 104 = 0x68
    int _restartAction;	// 108 = 0x6c
    NSString *_appPlaceholderPath;	// 112 = 0x70
    NSArray *_lockApplicationsDuringInstall;	// 120 = 0x78
    NSFileHandle *_translocationFileHandle;	// 128 = 0x80
    BOOL _isOSInstall;	// 136 = 0x88
    NSString *_masterBOMPath;	// 144 = 0x90
    unsigned long long _packageExtractorSpeed;	// 152 = 0x98
    NSDictionary *_untrustedEnvironment;	// 160 = 0xa0
    NSMachPort *_clientBootstrapPort;	// 168 = 0xa8
    NSMachPort *_clientSecuritySessionPort;	// 176 = 0xb0
    int _clientUID;	// 184 = 0xb8
    int _clientGID;	// 188 = 0xbc
    CDStruct_166d2db6 *_authorizationEnvironment;	// 192 = 0xc0
    struct AuthorizationOpaqueRef *_defaultAuthorization;	// 200 = 0xc8
    struct AuthorizationOpaqueRef *_overrideAuthorization;	// 208 = 0xd0
    int _minTrustLevel;	// 216 = 0xd8
    BOOL _allowExpiredCertificates;	// 220 = 0xdc
    BOOL _allowExpiredRoots;	// 221 = 0xdd
    BOOL _didPassPreflight;	// 222 = 0xde
    BOOL _hasValidTrustLevel;	// 223 = 0xdf
    int _evaluatedTrustLevel;	// 224 = 0xe0
    NSArray *_certificateChain;	// 232 = 0xe8
    struct __SecTrust *_trustRef;	// 240 = 0xf0
}

+ (BOOL)supportsSecureCoding;	// IMP=0x0000000000014da4
+ (id)requestWithPackages:(id)arg1 destination:(id)arg2;	// IMP=0x0000000000013ab8
@property long long installPhases; // @synthesize installPhases=_installPhases;
@property(retain) NSString *destinationPath; // @synthesize destinationPath=_destinationPath;
- (BOOL)_restrictedRootEnabled;	// IMP=0x00000000000161eb
- (BOOL)_restrictedRootOverridden;	// IMP=0x00000000000161cb
- (void)_setAppPlaceholderPath:(id)arg1;	// IMP=0x000000000001617f
- (id)_appPlaceholderPath;	// IMP=0x000000000001616e
- (void)_setClientBlocksRestart:(BOOL)arg1;	// IMP=0x000000000001615e
- (BOOL)_clientBlocksRestart;	// IMP=0x000000000001614d
- (void)_setSpaceRequiredForInstall:(unsigned long long)arg1;	// IMP=0x000000000001613c
- (unsigned long long)_spaceRequiredForInstall;	// IMP=0x000000000001612b
- (void)_setRestartAction:(int)arg1;	// IMP=0x000000000001611b
- (int)_restartAction;	// IMP=0x000000000001610b
- (void)_setAppStoreReceiptData:(id)arg1;	// IMP=0x00000000000160bf
- (id)_appStoreReceiptData;	// IMP=0x00000000000160ae
- (void)_setTranslocationFileHandle:(id)arg1;	// IMP=0x0000000000016062
- (void)_setLockApplicationsDuringInstall:(id)arg1;	// IMP=0x0000000000016012
- (id)_lockApplicationsDuringInstall;	// IMP=0x0000000000016001
- (void)_setIsRecursive:(BOOL)arg1;	// IMP=0x0000000000015ff1
- (BOOL)_isRecursive;	// IMP=0x0000000000015fe0
- (void)_setInternalBundleVersionChecking:(BOOL)arg1;	// IMP=0x0000000000015fd0
- (BOOL)_internalBundleVersionChecking;	// IMP=0x0000000000015fbf
- (void)_setUseHFSPlusCompressionByDefault:(BOOL)arg1;	// IMP=0x0000000000015faf
- (BOOL)_useHFSPlusCompressionByDefault;	// IMP=0x0000000000015f9e
- (unsigned long long)_extractionSpeed;	// IMP=0x0000000000015f8d
- (void)_setExtractionSpeed:(unsigned long long)arg1;	// IMP=0x0000000000015f7c
- (void)_setIgnoreIndexBom:(BOOL)arg1;	// IMP=0x0000000000015f6c
- (BOOL)_ignoreIndexBom;	// IMP=0x0000000000015f5b
- (void)_setUseOpenScriptsDirectory:(BOOL)arg1;	// IMP=0x0000000000015f4b
- (BOOL)_useOpenScriptsDirectory;	// IMP=0x0000000000015f3a
- (void)_setSkipsVerifyOnUnsignedPackages:(BOOL)arg1;	// IMP=0x0000000000015da0
- (void)_setMasterBOMPath:(id)arg1;	// IMP=0x0000000000015d54
- (id)_masterBOMPath;	// IMP=0x0000000000015d43
- (void)_setScriptTargetVolume:(id)arg1;	// IMP=0x0000000000015cf7
- (id)_scriptTargetVolume;	// IMP=0x0000000000015ce6
- (void)_setClientUID:(int)arg1 andGID:(int)arg2;	// IMP=0x0000000000015ccc
- (int)_clientGID;	// IMP=0x0000000000015cbc
- (int)_clientUID;	// IMP=0x0000000000015cac
- (void)_setClientSecuritySessionPort:(id)arg1;	// IMP=0x0000000000015c60
- (id)_clientSecuritySessionPort;	// IMP=0x0000000000015c4f
- (void)_setClientBootstrapPort:(id)arg1;	// IMP=0x0000000000015c03
- (id)_clientBootstrapPort;	// IMP=0x0000000000015bf2
- (void)_setUntrustedEnvironment:(id)arg1;	// IMP=0x0000000000015b82
- (id)_untrustedEnvironment;	// IMP=0x0000000000015b71
- (id)_installSandboxName;	// IMP=0x0000000000015b4c
- (void)_setInstallSandboxName:(id)arg1;	// IMP=0x0000000000015b46
- (BOOL)_isOSInstall;	// IMP=0x0000000000015b35
- (void)_setIsOSInstall:(BOOL)arg1;	// IMP=0x0000000000015b25
- (id)_clientProcessName;	// IMP=0x0000000000015b14
- (BOOL)_useForegroundPriorityForStaging;	// IMP=0x0000000000015b03
- (void)_setUseForegroundPriorityForStaging:(BOOL)arg1;	// IMP=0x0000000000015af3
- (BOOL)_isStageRequest;	// IMP=0x0000000000015ad6
- (void)_setIsStageRequest:(BOOL)arg1;	// IMP=0x0000000000015aaf
- (void)_setLoggingIdentifier:(id)arg1;	// IMP=0x0000000000015a68
- (id)_loggingIdentifier;	// IMP=0x0000000000015a32
- (id)_installItems;	// IMP=0x00000000000155db
- (void)removePackageSpecifiers:(id)arg1;	// IMP=0x0000000000015439
- (id)firmwareComponentsOfType:(long long)arg1;	// IMP=0x00000000000152af
- (id)packageSpecifiers;	// IMP=0x000000000001529e
- (id)packages;	// IMP=0x0000000000015121
- (id)description;	// IMP=0x00000000000150b1
- (BOOL)_isDeeplyEqualToRequest:(id)arg1;	// IMP=0x0000000000014fb4
- (BOOL)isEqual:(id)arg1;	// IMP=0x0000000000014f1c
- (void)dealloc;	// IMP=0x0000000000014daf
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000000001486e
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000000014001
- (id)_initWithPackages:(id)arg1 destination:(id)arg2;	// IMP=0x0000000000013bde
- (id)init;	// IMP=0x0000000000013b9f
- (id)initWithPackages:(id)arg1 destination:(id)arg2;	// IMP=0x0000000000013b0c
- (BOOL)_isRequestCompatibleWithRights:(id)arg1;	// IMP=0x00000000000168b6
- (BOOL)_validateAuthorizationReturningAcquiredRights:(id *)arg1;	// IMP=0x0000000000016665
- (BOOL)authorizeForRight:(const char *)arg1 allowingInteraction:(BOOL)arg2;	// IMP=0x00000000000165be
- (BOOL)preauthorizeAllowingInteraction:(BOOL)arg1;	// IMP=0x00000000000165a1
- (BOOL)requiresAuthorization;	// IMP=0x0000000000016555
- (int)_authLevel;	// IMP=0x0000000000016388
- (struct AuthorizationOpaqueRef *)authorization;	// IMP=0x0000000000016367
- (void)setAuthorizationEnvironment:(CDStruct_166d2db6 *)arg1;	// IMP=0x0000000000016356
- (void)setAuthorization:(struct AuthorizationOpaqueRef *)arg1;	// IMP=0x0000000000016345
- (struct AuthorizationOpaqueRef *)_createAuthorizationRefWithExternalFormData:(id)arg1;	// IMP=0x00000000000162dd
- (id)_externalFormDataForAuthorizationRef:(struct AuthorizationOpaqueRef *)arg1;	// IMP=0x0000000000016285
- (id)_authorizationAsExternalData;	// IMP=0x0000000000016254
- (int)trustLevelReturningTrustRef:(struct __SecTrust **)arg1;	// IMP=0x00000000000176e8
- (int)trustLevelReturningCertificateChain:(id *)arg1;	// IMP=0x000000000001769a
- (BOOL)evaluateTrustReturningError:(id *)arg1;	// IMP=0x00000000000173ab
- (BOOL)_evaluateTrustForPackage:(id)arg1 verifyingPayload:(BOOL)arg2 returningError:(id *)arg3;	// IMP=0x0000000000016f43
- (void)setAllowExpiredRoots:(BOOL)arg1;	// IMP=0x0000000000016f33
- (void)setAllowExpiredCertificates:(BOOL)arg1;	// IMP=0x0000000000016f23
- (void)setMinimumRequiredTrustLevel:(int)arg1;	// IMP=0x0000000000016f13
- (void)_updateWithSingleTrustLevel:(int)arg1 certificateChain:(id)arg2 trust:(struct __SecTrust *)arg3;	// IMP=0x0000000000016e73
- (void)_clearTrustEvaluation;	// IMP=0x0000000000016e0e
- (BOOL)_hasValidInstallPathForAnyIAPContent;	// IMP=0x0000000000017f55
- (BOOL)_isValidAppStoreRequest:(BOOL)arg1;	// IMP=0x0000000000017b45
- (BOOL)_isRequestFromMacAppStore;	// IMP=0x0000000000017b22
- (BOOL)_isRequestFromSoftwareUpdate;	// IMP=0x00000000000177b1
- (BOOL)_validAttributesForSoftwareUpdate:(id)arg1;	// IMP=0x0000000000017736
- (BOOL)didPassPreflightCheck;	// IMP=0x0000000000018d00
- (BOOL)_performPreflightCheckIncludingSizing:(BOOL)arg1 error:(id *)arg2;	// IMP=0x00000000000186a6
- (BOOL)_canInstallPackageSpecifier:(id)arg1 error:(id *)arg2;	// IMP=0x00000000000184b1
- (BOOL)performPreflightCheckReturningError:(id *)arg1;	// IMP=0x0000000000018494
- (unsigned long long)totalSizeRequired;	// IMP=0x00000000000182f8
- (void)_resolveInstallPathsReplacingPriorResults:(BOOL)arg1;	// IMP=0x00000000000181ad
- (BOOL)checkLocalPackagesReturningError:(id *)arg1;	// IMP=0x0000000000017f69

@end

