//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer, PKInstallRequest;

@interface PKInstallClient : NSObject
{
    PKInstallRequest *_installRequest;	// 8 = 0x8
    id _delegate;	// 16 = 0x10
    BOOL _delegateWantsUpdates;	// 24 = 0x18
    id _conn;	// 32 = 0x20
    id _installToken;	// 40 = 0x28
    NSTimer *_statusTimer;	// 48 = 0x30
    double _lastProgress;	// 56 = 0x38
    BOOL _isRegistering;	// 64 = 0x40
    BOOL _isInitialized;	// 65 = 0x41
}

+ (id)_connectToDaemonForAuthLevel:(int)arg1 privileged:(BOOL)arg2 recursiveInstall:(BOOL)arg3 silent:(BOOL)arg4 forInstance:(id)arg5;	// IMP=0x000000000000396e
+ (BOOL)isCurrentlyStagedInstallRequest:(id)arg1 purgeableSize:(id *)arg2;	// IMP=0x00000000000027ae
+ (double)estimatedTimeForInstallRequest:(id)arg1;	// IMP=0x00000000000026d0
+ (void)_modifyConnectionsForRegisteredAuthorizations:(id)arg1;	// IMP=0x000000000000247e
+ (void)unregisterAuthorizations;	// IMP=0x000000000000246a
+ (BOOL)registerAuthorization:(struct AuthorizationOpaqueRef *)arg1;	// IMP=0x0000000000001e00
+ (void)initialize;	// IMP=0x0000000000001ddf
+ (unsigned long long)purgeOrphanedSandboxesOnVolume:(id)arg1;	// IMP=0x0000000000004aee
+ (unsigned long long)purgeableSpaceForOrphanedSandboxesOnVolume:(id)arg1;	// IMP=0x0000000000004901
+ (unsigned long long)purgeSandboxesOnVolume:(id)arg1 purgeAmountNeeded:(unsigned long long)arg2 systemSandboxes:(BOOL)arg3;	// IMP=0x00000000000046eb
+ (unsigned long long)estimateOfPurgeableSpaceForSandboxesOnVolume:(id)arg1 systemSandboxes:(BOOL)arg2;	// IMP=0x00000000000044d1
- (void)installDidEndForToken:(id)arg1;	// IMP=0x00000000000044cb
- (void)installDidBeginCommitForToken:(id)arg1;	// IMP=0x00000000000044c5
- (void)installDidBeginForToken:(id)arg1;	// IMP=0x00000000000044a7
- (void)_installDaemonDidEndInstallWithError:(id)arg1 registrationPaths:(id)arg2;	// IMP=0x000000000000414c
- (id)_localPackageForRemoteSpecifier:(id)arg1;	// IMP=0x0000000000003fd9
- (void)_finishInstallClientOnMainThreadWithError:(id)arg1;	// IMP=0x0000000000003e9f
- (void)_statusTimerHasFired:(id)arg1;	// IMP=0x0000000000003ced
- (void)_scheduleStatusTimerOnCurrentThread;	// IMP=0x0000000000003c3e
- (id)_installStatusByConnectingToDaemon;	// IMP=0x0000000000003a49
- (void)_installDaemonDidBeginInstall_OnMainThread;	// IMP=0x0000000000003916
- (id)displayNames;	// IMP=0x0000000000003721
- (id)request;	// IMP=0x0000000000003710
- (void)dealloc;	// IMP=0x0000000000003657
- (id)_initWithRequest:(id)arg1 options:(unsigned long long)arg2 ignoringBlockingClients:(BOOL)arg3 delegate:(id)arg4 error:(id *)arg5;	// IMP=0x0000000000002bff
- (id)initWithRequest:(id)arg1 delegate:(id)arg2 options:(unsigned long long)arg3 error:(id *)arg4;	// IMP=0x0000000000002b86
- (id)initForCurrentCommitWithDelegate:(id)arg1 ignoringBlockingClients:(BOOL)arg2 error:(id *)arg3;	// IMP=0x0000000000002b58
- (id)initWithRequest:(id)arg1 inUserContext:(BOOL)arg2 holdingBoostDuringInstall:(BOOL)arg3 delegate:(id)arg4 error:(id *)arg5;	// IMP=0x0000000000002b24
- (id)initWithRequest:(id)arg1 inUserContext:(BOOL)arg2 delegate:(id)arg3 error:(id *)arg4;	// IMP=0x0000000000002afc
- (id)initWithRequest:(id)arg1 delegate:(id)arg2 error:(id *)arg3;	// IMP=0x0000000000002adf

@end

