//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface PKInstallSandboxManager : NSObject
{
    NSObject<OS_dispatch_queue> *_repoQueue;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_sandboxRemoveQueue;	// 16 = 0x10
}

+ (BOOL)_verboseMode;	// IMP=0x00000000000837a6
+ (id)_stagingCachePaths;	// IMP=0x00000000000827b5
+ (id)sharedSandboxManager;	// IMP=0x000000000007d47f
- (void)purgeSharedTemporaryDirectory;	// IMP=0x0000000000083760
- (id)pathToSharedTemporaryDirectoryCreating:(BOOL)arg1;	// IMP=0x00000000000835d0
- (long long)_relevanceOfSandbox:(id)arg1 forInstallingRequest:(id)arg2;	// IMP=0x0000000000082812
- (long long)_compareSandbox:(id)arg1 toSandbox:(id)arg2;	// IMP=0x0000000000082714
- (id)_inactiveSandboxesOnMountPoint:(id)arg1 forInstallingRequest:(id)arg2 appStoreOnly:(BOOL)arg3 forSystemSoftware:(BOOL)arg4 calculateRelevance:(BOOL)arg5 invalidSandboxPaths:(id *)arg6;	// IMP=0x000000000008215e
- (void)finishSandboxRemovalWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000000008209b
- (void)requestFreeSpace:(unsigned long long)arg1 onVolume:(id)arg2 forInstallingRequest:(id)arg3 appStoreOnly:(BOOL)arg4 forSystemSoftware:(BOOL)arg5 notifyOn:(id)arg6 withBlock:(CDUnknownBlockType)arg7;	// IMP=0x00000000000813e7
- (unsigned long long)irrelevantSpaceOnVolume:(id)arg1 forInstallingRequest:(id)arg2;	// IMP=0x0000000000081229
- (unsigned long long)purgeableSpaceOnVolume:(id)arg1 appStoreOnly:(BOOL)arg2 forSystemSoftware:(BOOL)arg3;	// IMP=0x0000000000080ece
- (unsigned long long)purgeOrphanedSpaceOnVolume:(id)arg1;	// IMP=0x0000000000080a47
- (unsigned long long)orphanedSpaceOnVolume:(id)arg1;	// IMP=0x00000000000807d1
- (unsigned long long)purgeableSpaceOnVolume:(id)arg1 appStoreOnly:(BOOL)arg2;	// IMP=0x00000000000807bc
- (unsigned long long)purgeableSpaceOnVolume:(id)arg1;	// IMP=0x00000000000807a8
- (BOOL)_canCreateDirectoryUnder:(id)arg1;	// IMP=0x0000000000080739
- (id)_repositoryParentPathForRootVolume;	// IMP=0x00000000000806a9
- (id)_sandboxRepositoryForDestination:(id)arg1 forSystemSoftware:(BOOL)arg2 create:(BOOL)arg3 error:(id *)arg4;	// IMP=0x00000000000803f7
- (BOOL)_removeSandbox:(id)arg1;	// IMP=0x0000000000080247
- (id)_trashSandboxAtPath:(id)arg1;	// IMP=0x000000000007ffa2
- (id)_deactivateSandboxAtPath:(id)arg1;	// IMP=0x000000000007fcfd
- (id)_activateSandboxAtPath:(id)arg1 error:(id *)arg2;	// IMP=0x000000000007f93f
- (id)_orphanedSandboxPathsOnVolume:(id)arg1;	// IMP=0x000000000007f67c
- (id)_bootSessionUUID;	// IMP=0x000000000007f5e5
- (id)_addSandboxPathForDestination:(id)arg1 forSystemSoftware:(BOOL)arg2;	// IMP=0x000000000007f2dd
- (id)_anySandboxPathForDestination:(id)arg1 forSystemSoftware:(BOOL)arg2;	// IMP=0x000000000007efbb
- (id)_activeSandboxPathsForDestination:(id)arg1 forSystemSoftware:(BOOL)arg2;	// IMP=0x000000000007ecd5
- (id)_currentSandboxPathsForDestination:(id)arg1 forSystemSoftware:(BOOL)arg2;	// IMP=0x000000000007e9ef
- (id)_sandboxAtPath:(id)arg1 matchingRequest:(id)arg2 forUse:(BOOL)arg3;	// IMP=0x000000000007e505
- (id)_statePathForSandboxAtPath:(id)arg1;	// IMP=0x000000000007e4e6
- (BOOL)hasStagedSandboxForRequest:(id)arg1;	// IMP=0x000000000007e33e
- (void)discardSandbox:(id)arg1;	// IMP=0x000000000007e247
- (BOOL)saveSandboxAsStaged:(id)arg1;	// IMP=0x000000000007e153
- (BOOL)_saveSandboxState:(id)arg1 sessionIDOnly:(BOOL)arg2;	// IMP=0x000000000007ded3
- (id)_sessionUUIDFilePathForSandboxAtPath:(id)arg1;	// IMP=0x000000000007deb4
- (id)_sessionUUIDForSandboxPath:(id)arg1 oSandboxCreationDate:(id *)arg2;	// IMP=0x000000000007dd7e
- (id)sandboxForRequest:(id)arg1 created:(char *)arg2 error:(id *)arg3;	// IMP=0x000000000007d609
- (void)dealloc;	// IMP=0x000000000007d590
- (id)init;	// IMP=0x000000000007d4e2

@end

