//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSDate, NSError, NSNumber, PKInstallAnalyzer, PKInstallRequest, PKInstallSandbox;

@interface PKInstallOperation : NSOperation
{
    PKInstallRequest *_request;	// 24 = 0x18
    PKInstallSandbox *_sandbox;	// 32 = 0x20
    PKInstallAnalyzer *_analyzer;	// 40 = 0x28
    NSNumber *_originalEstimate;	// 48 = 0x30
    NSError *_error;	// 56 = 0x38
    NSDate *_startDate;	// 64 = 0x40
    NSDate *_packageStartDate;	// 72 = 0x48
}

@property(retain) NSError *error; // @synthesize error=_error;
@property(readonly, retain) NSDate *startDate; // @synthesize startDate=_startDate;
@property(readonly, retain) PKInstallAnalyzer *analyzer; // @synthesize analyzer=_analyzer;
@property(readonly, retain) PKInstallSandbox *sandbox; // @synthesize sandbox=_sandbox;
@property(readonly, retain) PKInstallRequest *request; // @synthesize request=_request;
- (id)taskWithLaunchPath:(id)arg1 arguments:(id)arg2 currentDirectoryPath:(id)arg3 logWithPrefix:(id)arg4;	// IMP=0x000000000005ae21
- (void)logResult:(long long)arg1;	// IMP=0x000000000005ac30
- (id)messageTracerTernarySignature;	// IMP=0x000000000005ac28
- (id)messageTracerComment;	// IMP=0x000000000005abf5
- (id)messageTracerDomain;	// IMP=0x000000000005abc2
- (id)currentPackageSpecifier;	// IMP=0x000000000005abba
- (id)currentPackage;	// IMP=0x000000000005ab8f
- (int)installState;	// IMP=0x000000000005ab5c
@property double totalEstimatedTime;
- (double)estimatedTimeRemaining;	// IMP=0x000000000005aa29
- (void)start;	// IMP=0x000000000005a9a6
- (id)description;	// IMP=0x000000000005a929
- (void)dealloc;	// IMP=0x000000000005a85e
- (id)initWithRequest:(id)arg1 sandbox:(id)arg2 analyzer:(id)arg3;	// IMP=0x000000000005a78f
- (id)completionSummary;	// IMP=0x000000000005afb8

@end

