//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableArray, NSMutableDictionary, NSMutableSet, PKInstallRequest;

@interface PKInstallAnalyzer : NSObject
{
    PKInstallRequest *_installRequest;	// 8 = 0x8
    NSMutableDictionary *_maskPathsByPackageSpecifier;	// 16 = 0x10
    NSMutableDictionary *_skipComponentsByPackageSpecifier;	// 24 = 0x18
    NSMutableSet *_obsoletedFiles;	// 32 = 0x20
    NSMutableSet *_potentiallyObsoleteDirectories;	// 40 = 0x28
    NSMutableSet *_atomicallyObsoleteBundles;	// 48 = 0x30
    NSMutableSet *_truncateBeforeObsoletingFiles;	// 56 = 0x38
    NSMutableArray *_deferredInstallPaths;	// 64 = 0x40
    NSMutableArray *_registrationPaths;	// 72 = 0x48
    NSMutableArray *_contentCachingPaths;	// 80 = 0x50
    long long _kextPathCount;	// 88 = 0x58
    long long _systemLibraryCount;	// 96 = 0x60
    long long _xpcCachePathCount;	// 104 = 0x68
    NSDictionary *_bundlePathToComponentMap;	// 112 = 0x70
    NSMutableDictionary *_bundleIdentToXATTRMap;	// 120 = 0x78
}

- (void)_findRegistrationPathsForPackageSpecifier:(id)arg1;	// IMP=0x0000000000049f9b
- (void)_findDeferredInstallPathsForPackageSpecifier:(id)arg1;	// IMP=0x0000000000049cb3
- (void)_findMaskPathsAndSkipComponentsForPackageSpecifier:(id)arg1;	// IMP=0x0000000000049953
- (BOOL)_shouldInstallPackageComponent:(id)arg1 forPackageSpecifier:(id)arg2;	// IMP=0x00000000000492cd
- (id)_versionPreviouslyDeferredForComponentAtPath:(id *)arg1;	// IMP=0x0000000000048cec
- (id)_buildBundlePathToComponentMapForRequest;	// IMP=0x00000000000488b8
- (void)_findObsoleteOnDiskFilesForPackageSpecifier:(id)arg1;	// IMP=0x0000000000046de8
- (BOOL)_shouldAllowReceiptBasedFileObsoletingForPackage:(id)arg1;	// IMP=0x0000000000046ab6
- (BOOL)_isUnsafeToObsoleteComponent:(id)arg1;	// IMP=0x000000000004698d
- (id)extendedAttributesForComponent:(id)arg1;	// IMP=0x0000000000046951
- (BOOL)installsXPCCacheContent;	// IMP=0x0000000000046939
- (BOOL)installsSystemLibraries;	// IMP=0x0000000000046921
- (BOOL)installsKexts;	// IMP=0x0000000000046909
- (id)bundlePathsForContentCaching;	// IMP=0x00000000000468f8
- (id)bundlePathsForRegistration;	// IMP=0x00000000000468e7
- (id)deferredInstallPaths;	// IMP=0x00000000000468d6
- (id)atomicallyObsoletePaths;	// IMP=0x00000000000468c5
- (id)potentiallyObsoleteDirectories;	// IMP=0x00000000000468b4
- (id)truncateBeforeObsoletingFiles;	// IMP=0x00000000000468a3
- (id)obsoletedFiles;	// IMP=0x0000000000046892
- (id)skipComponentsForPackageSpecifier:(id)arg1;	// IMP=0x0000000000046875
- (id)maskPathsForPackageSpecifier:(id)arg1;	// IMP=0x0000000000046858
- (void)_sanitizePackageDataForRequest;	// IMP=0x00000000000464e6
- (void)_analyzeIncludingObsoletion:(BOOL)arg1;	// IMP=0x000000000004623b
- (void)dealloc;	// IMP=0x000000000004611b
- (id)initWithInstallRequest:(id)arg1 includeObsoletion:(BOOL)arg2;	// IMP=0x0000000000045f00
- (id)initWithInstallRequest:(id)arg1;	// IMP=0x0000000000045ee9

@end

