//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PKInstallHistory : NSObject
{
    NSString *_path;	// 8 = 0x8
}

+ (id)defaultHistory;	// IMP=0x0000000000044ed0
+ (id)historyOnVolume:(id)arg1;	// IMP=0x00000000000451a2
- (id)installedItems;	// IMP=0x0000000000045161
- (BOOL)addInstallRequest:(id)arg1;	// IMP=0x0000000000044f1a
- (void)dealloc;	// IMP=0x0000000000044e69
- (id)initWithPath:(id)arg1;	// IMP=0x0000000000044df0

@end

