//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PKInstallStateHelper : NSObject
{
}

+ (id)localizedDescriptionForInstallState:(int)arg1;	// IMP=0x00000000000017f0
+ (id)stringFromInstallState:(int)arg1;	// IMP=0x00000000000016c0

@end

