//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSFileHandle, NSString, NSTask;

@interface PKInstallTask : NSObject
{
    NSTask *_task;	// 8 = 0x8
    NSString *_logPrefix;	// 16 = 0x10
    NSFileHandle *_outputReadHandle;	// 24 = 0x18
    NSString *_partialLine;	// 32 = 0x20
    BOOL _logOnlyStandardError;	// 40 = 0x28
}

@property BOOL logOnlyStandardError; // @synthesize logOnlyStandardError=_logOnlyStandardError;
- (BOOL)_processTaskOutput:(id)arg1;	// IMP=0x000000000004595c
- (void)_readTaskOutput:(id)arg1;	// IMP=0x00000000000458fc
- (void)_flushTaskOutput;	// IMP=0x0000000000045804
- (int)run;	// IMP=0x0000000000045550
- (id)task;	// IMP=0x000000000004553f
- (void)dealloc;	// IMP=0x0000000000045475
- (id)initWithTask:(id)arg1 logWithPrefix:(id)arg2;	// IMP=0x000000000004536a

@end

