//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_source>, NSString, NSTask, PKInstallRequest;

@interface PKInstallCommitManager : NSObject
{
    PKInstallRequest *_installRequest;	// 8 = 0x8
    NSString *_pidPath;	// 16 = 0x10
    BOOL _suspendedSpotlight;	// 24 = 0x18
    NSObject<OS_dispatch_source> *_backupTimerSource;	// 32 = 0x20
    unsigned int _assertionID;	// 40 = 0x28
    NSTask *_monitorTask;	// 48 = 0x30
}

- (void)_waitUntilMonitorDone;	// IMP=0x00000000000862ad
- (void)_startMonitor;	// IMP=0x0000000000086110
- (id)_commitCookiePath;	// IMP=0x0000000000086081
- (void)endCommit;	// IMP=0x0000000000085f6b
- (void)beginCommit;	// IMP=0x00000000000857c9
- (void)dealloc;	// IMP=0x0000000000085703
- (id)initWithRequest:(id)arg1;	// IMP=0x000000000008567c

@end

