//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSXPCListenerDelegate.h"
#import "PKInstallService.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, NSXPCListener;

@interface PKInstallDaemon : NSObject <PKInstallService, NSXPCListenerDelegate>
{
    NSXPCListener *_listener;	// 8 = 0x8
    NSString *_connectionName;	// 16 = 0x10
    NSMutableDictionary *_tokenToInstallDictionary;	// 24 = 0x18
    NSMutableDictionary *_tokenToDoneBlockDictionary;	// 32 = 0x20
    NSMutableDictionary *_tokenToQualityOfServiceClassDictionary;	// 40 = 0x28
    id _currentToken;	// 48 = 0x30
    NSMutableArray *_tokenQueue;	// 56 = 0x38
    NSMutableDictionary *_validatedAuthorizations;	// 64 = 0x40
    NSMutableArray *_clients;	// 72 = 0x48
    NSObject<OS_dispatch_queue> *_queueQueue;	// 80 = 0x50
    NSObject<OS_dispatch_queue> *_serviceQueue;	// 88 = 0x58
    NSObject<OS_dispatch_queue> *_clientNotifyQueue;	// 96 = 0x60
    NSObject<OS_dispatch_queue> *_stateQueue;	// 104 = 0x68
    int _daemonState;	// 112 = 0x70
    int _idleCount;	// 116 = 0x74
}

+ (BOOL)doingRecursiveInstall;	// IMP=0x000000000000820f
+ (id)sharedServiceDaemon;	// IMP=0x0000000000005579
- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x0000000000009195
- (void)_runIdleTasks;	// IMP=0x0000000000008f4d
- (BOOL)_isProvidingPrivilegeEscalation;	// IMP=0x0000000000008ef5
- (BOOL)_shouldOnlyInstallSystemSoftwareForRequest:(id)arg1;	// IMP=0x0000000000008ea5
- (BOOL)_requestHasValidAuthorization:(id)arg1 allowInteraction:(BOOL)arg2;	// IMP=0x0000000000008dca
- (BOOL)_evaluateSecurityOfRequest:(id)arg1;	// IMP=0x0000000000008d3f
- (void)_invokeDoneBlocksForToken:(id)arg1;	// IMP=0x00000000000087c6
- (void)_attachToToken:(id)arg1 withDoneBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000000000085be
- (BOOL)removeTokenIfPossible:(id)arg1;	// IMP=0x0000000000008368
- (void)startNextInstallIfNeeded;	// IMP=0x000000000000801d
- (id)_currentClients;	// IMP=0x0000000000007e67
- (void)purgeOrphanedSandboxesOnVolume:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000000007d3d
- (void)purgeableSpaceForOrphanedSandboxesOnVolume:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000000007c13
- (void)startPurgeOfSandboxesOnVolume:(id)arg1 purgeAmountNeeded:(unsigned long long)arg2 systemSandboxes:(BOOL)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x00000000000079f7
- (void)estimateOfPurgeableSpaceForSandboxesOnVolume:(id)arg1 systemSandboxes:(BOOL)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x00000000000078b4
- (void)currentStageStatusOfInstallRequest:(id)arg1 calculatePurgeableSize:(BOOL)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0000000000007698
- (void)registerAuthorizationFromInstallRequest:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00000000000074db
- (void)adoptToken:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00000000000073bc
- (void)tokenForCurrentCommitIgnoringBlockingClients:(BOOL)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000000006e44
- (void)displayNamesForToken:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000000000699e
- (void)installStatusForToken:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00000000000064b0
- (void)addToken:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000000000604c
- (void)tokenForInstallRequest:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000000005bb8
@property(readonly, copy) NSString *description;
- (id)_descriptionForToken:(id)arg1;	// IMP=0x000000000000599f
- (void)startListeningForConnectionsToService:(id)arg1;	// IMP=0x0000000000005909
- (void)dealloc;	// IMP=0x0000000000005789
- (id)init;	// IMP=0x00000000000055dc
- (void)installDidCancel:(id)arg1;	// IMP=0x0000000000009fa7
- (void)installDidFinish:(id)arg1;	// IMP=0x0000000000009f95
- (void)install:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x0000000000009f83
- (void)_installDidEnd;	// IMP=0x0000000000009af8
- (void)installWillFinish:(id)arg1;	// IMP=0x00000000000098b5
- (void)installDidBegin:(id)arg1;	// IMP=0x0000000000009672

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

