//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, PKInstallAnalyzer, PKInstallRequest;

@interface PKInstallManifest : NSObject
{
    PKInstallRequest *_installRequest;	// 8 = 0x8
    PKInstallAnalyzer *_installAnalyzer;	// 16 = 0x10
    NSDictionary *_defaultPathByBundleIdentifier;	// 24 = 0x18
    NSDictionary *_actualPathByBundleIdentifier;	// 32 = 0x20
    NSDictionary *_versionByBundleIdentifier;	// 40 = 0x28
    NSDictionary *_downgradePathByBundleIdentifier;	// 48 = 0x30
    NSArray *_topBundleIdentifiers;	// 56 = 0x38
    NSArray *_actualFileInstallPaths;	// 64 = 0x40
    NSArray *_actualInstallPathsForSystemContent;	// 72 = 0x48
}

- (void)_processAnalysis;	// IMP=0x0000000000070be6
- (id)actualInstallPathsForSystemContent;	// IMP=0x0000000000070829
- (id)downgradePathForBundleIdentifier:(id)arg1;	// IMP=0x0000000000070804
- (id)installedVersionForBundleIdentifier:(id)arg1;	// IMP=0x00000000000707df
- (id)actualInstallPathForBundleIdentifier:(id)arg1;	// IMP=0x00000000000707ba
- (id)defaultInstallPathForBundleIdentifier:(id)arg1;	// IMP=0x0000000000070795
- (id)topBundleIdentifiers;	// IMP=0x0000000000070784
- (id)bundleIdentifiers;	// IMP=0x0000000000070767
- (void)dealloc;	// IMP=0x000000000007067a
- (id)initWithInstallRequest:(id)arg1;	// IMP=0x000000000007057e

@end

