//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKPackage.h>

@class NSBundle;

@interface PKJaguarPackage : PKPackage
{
    NSBundle *_bundle;	// 56 = 0x38
}

+ (BOOL)_isArchiveSupported:(id)arg1;	// IMP=0x000000000001fc60
+ (id)_payloadForPackagePath:(id)arg1;	// IMP=0x000000000001fbc9
+ (BOOL)canInitWithURL:(id)arg1;	// IMP=0x000000000001e8fb
- (id)_parseHintsFile:(id)arg1;	// IMP=0x000000000001fe63
- (id)payloadExtractorWithDestination:(id)arg1 externalRoot:(id)arg2 error:(id *)arg3;	// IMP=0x000000000001fd9c
- (id)BOMData;	// IMP=0x000000000001fd44
- (id)_resourceRelativePathForScript:(id)arg1;	// IMP=0x000000000001fb3e
- (id)_postupgradeScriptPath;	// IMP=0x000000000001fb25
- (id)_preupgradeScriptPath;	// IMP=0x000000000001fb0c
- (id)_postflightScriptPath;	// IMP=0x000000000001faf3
- (id)_preflightScriptPath;	// IMP=0x000000000001fada
- (id)_scriptsDirectory;	// IMP=0x000000000001fabd
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000000001fa44
- (void)dealloc;	// IMP=0x000000000001f9dd
- (id)initWithURL:(id)arg1;	// IMP=0x000000000001e953

@end

