//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@interface PKKextCacheInstallOperation : PKInstallOperation
{
}

- (void)main;	// IMP=0x0000000000062ab1
- (BOOL)_updateKextCachesReturningError:(id *)arg1;	// IMP=0x00000000000627e3
- (int)installState;	// IMP=0x00000000000627d8
- (BOOL)_shouldUpdateKextCaches;	// IMP=0x0000000000062738
- (id)initWithRequest:(id)arg1 sandbox:(id)arg2 analyzer:(id)arg3;	// IMP=0x00000000000626aa

@end

