//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKPackage.h>

@interface PKLeopardPackage : PKPackage
{
}

- (id)scriptsExtractorWithDestination:(id)arg1 error:(id *)arg2;	// IMP=0x00000000000206bc
- (id)scriptsSubpath;	// IMP=0x00000000000206af
- (id)payloadExtractorWithDestination:(id)arg1 externalRoot:(id)arg2 error:(id *)arg3;	// IMP=0x00000000000203f1
- (id)BOMData;	// IMP=0x00000000000203a0
- (id)initWithURL:(id)arg1;	// IMP=0x0000000000020264
- (id)_archiveSubpathWithFileName:(id)arg1;	// IMP=0x000000000002020e

@end

