//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@interface PKLSRegisterInstallOperation : PKInstallOperation
{
}

+ (BOOL)registerWithLaunchServices:(id)arg1;	// IMP=0x0000000000062d33
- (void)main;	// IMP=0x0000000000062cd2
- (BOOL)_registerLaunchServicesBundlesReturningError:(id *)arg1;	// IMP=0x0000000000062b1d
- (int)installState;	// IMP=0x0000000000062b12

@end

