//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKProduct.h>

@interface PKMutableProduct : PKProduct
{
}

- (BOOL)commitReturningError:(id *)arg1;	// IMP=0x000000000004379b
- (BOOL)writeToArchive:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000043768
- (BOOL)writeProduct;	// IMP=0x0000000000043735
- (BOOL)unregisterPackageReference:(id)arg1 deletePackage:(BOOL)arg2;	// IMP=0x0000000000043702
- (BOOL)registerPackageReference:(id)arg1;	// IMP=0x00000000000436cf
- (id)suggestedPackagePathFromPackageReference:(id)arg1;	// IMP=0x000000000004369c
- (BOOL)addResourceDataAtPath:(id)arg1;	// IMP=0x0000000000043669
- (BOOL)setDistributionFromContainer:(id)arg1;	// IMP=0x0000000000043636
- (BOOL)setDistribution:(id)arg1;	// IMP=0x0000000000043603
- (void)setProductIdentifier:(id)arg1 version:(id)arg2;	// IMP=0x00000000000435fd
- (id)initForWritingToArchive:(id)arg1 ofType:(id)arg2 signingDelegate:(id)arg3 error:(id *)arg4;	// IMP=0x0000000000043408
- (id)initForWritingToArchive:(id)arg1 ofType:(id)arg2 error:(id *)arg3;	// IMP=0x00000000000433ed
- (BOOL)_setDistributionFlatData:(id)arg1;	// IMP=0x00000000000438e1
- (BOOL)_setDistributionArchiveFromPath:(id)arg1;	// IMP=0x00000000000438d9
- (id)_initForWritingAtPath:(id)arg1 ofType:(id)arg2 error:(id *)arg3;	// IMP=0x00000000000437ce
- (void)_setInstallerPluginsPath:(id)arg1;	// IMP=0x00000000000438ef
- (void)_setScriptsPath:(id)arg1;	// IMP=0x00000000000438e9

@end

