//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKBOM.h>

@interface PKMutableBOM : PKBOM
{
}

- (BOOL)_addAppleDoubleAsNeededForForDirectory:(id)arg1 includeACLs:(BOOL)arg2;	// IMP=0x000000000001c772
- (BOOL)_addAppleDoubleForFile:(id)arg1 forBOMPath:(id)arg2;	// IMP=0x000000000001c640
- (BOOL)_needAppleDoubleForPath:(id)arg1 includeACLs:(BOOL)arg2;	// IMP=0x000000000001c5f8
- (BOOL)commitData;	// IMP=0x000000000001c5da
- (BOOL)setAttributes:(id)arg1 ofItemAtPath:(id)arg2;	// IMP=0x000000000001c54b
- (BOOL)addFile:(id)arg1 forBomPath:(id)arg2 includeACLs:(BOOL)arg3;	// IMP=0x000000000001c3cb
- (BOOL)addBomPath:(id)arg1 fileType:(id)arg2;	// IMP=0x000000000001c234
- (id)initWithDirectory:(id)arg1 writingToPath:(id)arg2 includeACLs:(BOOL)arg3 maskPatterns:(id)arg4;	// IMP=0x000000000001c0fb
- (struct __CFArray *)_newBOMPatternList:(id)arg1;	// IMP=0x000000000001bf98
- (id)initForWritingToPath:(id)arg1;	// IMP=0x000000000001be99

@end

