//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKPackage.h>

@class NSArray, NSString;

@interface PKMutablePackage : PKPackage
{
    NSArray *_onDiskComponents;	// 56 = 0x38
    NSString *_payloadRoot;	// 64 = 0x40
    NSString *_baselinePayloadRoot;	// 72 = 0x48
    NSString *_scriptRoot;	// 80 = 0x50
    NSArray *_maskExpressions;	// 88 = 0x58
    CDUnknownBlockType _ownershipModifier;	// 96 = 0x60
    CDUnknownBlockType _baselineNameMapper;	// 104 = 0x68
}

- (BOOL)writeToArchive:(id)arg1 options:(id)arg2 error:(id *)arg3;	// IMP=0x00000000000226ef
- (BOOL)writeToArchive:(id)arg1 error:(id *)arg2;	// IMP=0x00000000000226a3
- (void)setModifyOwnershipUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000000022673
- (void)setMaskExpressions:(id)arg1;	// IMP=0x0000000000022643
- (void)setScriptRoot:(id)arg1;	// IMP=0x0000000000022613
- (void)setPayloadRoot:(id)arg1;	// IMP=0x00000000000225e3
- (void)setComponents:(id)arg1;	// IMP=0x00000000000225b3
- (id)_componentMap;	// IMP=0x0000000000022582
- (void)dealloc;	// IMP=0x00000000000224a6
- (id)initWithPackageInfo:(id)arg1 ofType:(id)arg2;	// IMP=0x0000000000022435
- (void)setMapBaselineNamesUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000000000268bb
- (void)setBaselinePayloadRoot:(id)arg1;	// IMP=0x000000000002688b
- (BOOL)_writeToArchive:(id)arg1 atPath:(id)arg2 options:(id)arg3 error:(id *)arg4;	// IMP=0x0000000000026858
- (id)initWithPackageInfo:(id)arg1;	// IMP=0x00000000000267ca

@end

