//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKReceipt.h>

@class NSData;

@interface PKMutableReceipt : PKReceipt
{
    NSData *_bomData;	// 48 = 0x30
}

- (BOOL)writeToDestination:(id)arg1 forSystemContent:(BOOL)arg2 error:(id *)arg3;	// IMP=0x000000000002f2f1
- (BOOL)writeToSandboxRoot:(id)arg1 destination:(id)arg2 forSystemContent:(BOOL)arg3 error:(id *)arg4;	// IMP=0x000000000002f27b
- (BOOL)writeToDirectory:(id)arg1 error:(id *)arg2;	// IMP=0x000000000002f261
- (BOOL)_writeToDirectory:(id)arg1 forSystemContent:(BOOL)arg2 error:(id *)arg3;	// IMP=0x000000000002ef4a
- (id)_BOM;	// IMP=0x000000000002eeee
- (void)dealloc;	// IMP=0x000000000002ee87
- (id)initWithPackageIdentifier:(id)arg1 packageVersion:(id)arg2 BOMData:(id)arg3;	// IMP=0x000000000002ed6b

@end

