//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKXARArchive.h>

@class NSMutableArray;

@interface PKMutableXARArchive : PKXARArchive
{
    NSMutableArray *_signers;	// 32 = 0x20
    BOOL _mutable;	// 40 = 0x28
}

- (BOOL)setContentsOfArchive:(id)arg1 forPath:(id)arg2;	// IMP=0x000000000000e932
- (BOOL)setFile:(id)arg1 forPath:(id)arg2 compressed:(BOOL)arg3;	// IMP=0x000000000000e83a
- (BOOL)setData:(id)arg1 forPath:(id)arg2 compressed:(BOOL)arg3;	// IMP=0x000000000000e72c
- (struct __xar_file_t *)_fileStructForParentOfSubpath:(id)arg1 error:(id *)arg2;	// IMP=0x000000000000e5a8
- (BOOL)closeArchive;	// IMP=0x000000000000e552
- (void)dealloc;	// IMP=0x000000000000e4d9
- (id)initForWritingToPath:(id)arg1 error:(id *)arg2;	// IMP=0x000000000000e2ae
- (void)setSignatureSize:(int)arg1;	// IMP=0x000000000000f08f
- (BOOL)addIntermediateCertificate:(struct OpaqueSecCertificateRef *)arg1;	// IMP=0x000000000000effc
- (BOOL)addSignatureBySigningWithIdentity:(struct OpaqueSecIdentityRef *)arg1 algorithm:(id)arg2 usingTSAIfSupported:(BOOL)arg3;	// IMP=0x000000000000ed20

@end

