//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKDistributionContainer.h>

@class NSError;

@interface PKMutableDistributionContainer : PKDistributionContainer
{
    NSError *_error;	// 16 = 0x10
}

@property(retain) NSError *error; // @synthesize error=_error;
- (BOOL)commitReturningError:(id *)arg1;	// IMP=0x0000000000056825
- (BOOL)storeResourcesAtPath:(id)arg1 forLocalization:(id)arg2;	// IMP=0x000000000005633e
- (BOOL)setResourceData:(id)arg1 forKey:(id)arg2 forLocalization:(id)arg3;	// IMP=0x000000000005630b
- (BOOL)setStringsData:(id)arg1 forLocalization:(id)arg2;	// IMP=0x00000000000562d8
- (BOOL)setDistributionFromContainer:(id)arg1;	// IMP=0x00000000000562a5
- (void)setDistribution:(id)arg1;	// IMP=0x0000000000056259
- (id)initForWritingToArchive:(id)arg1;	// IMP=0x0000000000056211
- (id)initForWritingToPath:(id)arg1;	// IMP=0x00000000000561c9

@end

