//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKMutableProduct.h>

@class NSData, NSString, NSURL, PKDistribution, PKDistributionContainer, PKProductInfo;

@interface PKNetEnabledProduct : PKMutableProduct
{
    NSURL *_url;	// 40 = 0x28
    PKProductInfo *_productInfo;	// 48 = 0x30
    NSData *_distributionData;	// 56 = 0x38
    PKDistributionContainer *_container;	// 64 = 0x40
    PKDistribution *_fromDistribution;	// 72 = 0x48
    PKDistributionContainer *_fromContainer;	// 80 = 0x50
    NSString *_resourcePath;	// 88 = 0x58
    id <PKMutableProductSigningDelegate> _signingDelegate;	// 96 = 0x60
}

+ (id)_standardizedProductURL:(id)arg1;	// IMP=0x0000000000041763
+ (id)productInfoFilename;	// IMP=0x0000000000041756
- (BOOL)commitReturningError:(id *)arg1;	// IMP=0x0000000000042a8d
- (BOOL)unregisterPackageReference:(id)arg1 deletePackage:(BOOL)arg2;	// IMP=0x0000000000042942
- (BOOL)registerPackageReference:(id)arg1;	// IMP=0x00000000000426fc
- (BOOL)commitProductInfo;	// IMP=0x0000000000042670
- (id)suggestedPackagePathFromPackageReference:(id)arg1;	// IMP=0x00000000000425b3
- (BOOL)_populateWithFlattenedDistributionsReturningError:(id *)arg1;	// IMP=0x0000000000042139
- (id)_distributionWriteURLForLocalization:(id)arg1;	// IMP=0x0000000000042077
- (BOOL)addResourceDataAtPath:(id)arg1;	// IMP=0x0000000000042026
- (BOOL)_setDistributionFlatData:(id)arg1;	// IMP=0x000000000004201e
- (BOOL)setDistributionFromContainer:(id)arg1;	// IMP=0x0000000000041fcd
- (BOOL)setDistribution:(id)arg1;	// IMP=0x0000000000041f7c
- (void)setProductIdentifier:(id)arg1 version:(id)arg2;	// IMP=0x0000000000041f5f
- (id)initForWritingAtPath:(id)arg1 signingDelegate:(id)arg2 error:(id *)arg3;	// IMP=0x0000000000041d86
- (id)allPackageReferences;	// IMP=0x0000000000041d69
- (id)localizedStringForKey:(id)arg1 value:(id)arg2;	// IMP=0x0000000000041d4c
- (id)stringsDictionary;	// IMP=0x0000000000041d2f
- (id)_distributionFlatData;	// IMP=0x0000000000041d1e
- (id)distributionContainer;	// IMP=0x0000000000041d0d
- (id)distribution;	// IMP=0x0000000000041cf0
- (id)productVersion;	// IMP=0x0000000000041cd3
- (id)productIdentifier;	// IMP=0x0000000000041cb6
- (id)productType;	// IMP=0x0000000000041ca6
- (id)URL;	// IMP=0x0000000000041c95
- (id)description;	// IMP=0x0000000000041c3f
- (void)dealloc;	// IMP=0x0000000000041b63
- (BOOL)didReceiveData:(id)arg1 fromDistributionURL:(id)arg2 error:(id *)arg3;	// IMP=0x0000000000041ae2
- (id)initByLoadingProductAtURL:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000041846

@end

