//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@interface PKObsoletionInstallOperation : PKInstallOperation
{
}

- (void)main;	// IMP=0x0000000000060633
- (BOOL)_removeAppPlaceholderReturningError:(id *)arg1;	// IMP=0x000000000006053a
- (BOOL)_deleteObsoletePathsReturningError:(id *)arg1;	// IMP=0x0000000000060050
- (BOOL)_trashAtomicallyObsoleteBundlesReturningError:(id *)arg1;	// IMP=0x000000000005fd4a
- (BOOL)_shouldDeleteDirectoryAtPath:(id)arg1;	// IMP=0x000000000005fca3
- (int)installState;	// IMP=0x000000000005fc98

@end

