//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSArray, NSDictionary, NSURL, PKArchive, PKPackageInfo;

@interface PKPackage : NSObject <NSCoding, NSCopying>
{
    NSURL *_url;	// 8 = 0x8
    PKArchive *_archive;	// 16 = 0x10
    PKPackageInfo *_packageInfo;	// 24 = 0x18
    NSDictionary *_componentMap;	// 32 = 0x20
    NSArray *_firmwareBundleComponents;	// 40 = 0x28
    BOOL _populatedSubpaths;	// 48 = 0x30
}

+ (id)packageWithURL:(id)arg1;	// IMP=0x0000000000020c48
+ (id)packageWithPath:(id)arg1;	// IMP=0x0000000000020c02
+ (id)_allPackageClasses;	// IMP=0x0000000000020ba2
+ (BOOL)canInitWithURL:(id)arg1;	// IMP=0x0000000000026684
- (void)enumerateBundleComponentsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000000021fcd
- (void)_populateComponentSubpaths;	// IMP=0x00000000000216db
- (id)fileURL;	// IMP=0x00000000000216ca
- (id)archive;	// IMP=0x00000000000216b9
- (BOOL)extractFilesForBundleComponent:(id)arg1 toPath:(id)arg2 error:(id *)arg3;	// IMP=0x0000000000021570
- (id)firmwareComponentsOfType:(long long)arg1;	// IMP=0x00000000000213d0
- (id)firmwareComponents;	// IMP=0x0000000000021364
- (id)subpathsForComponent:(id)arg1;	// IMP=0x0000000000021336
- (id)componentForIdentifier:(id)arg1;	// IMP=0x0000000000021305
- (id)components;	// IMP=0x00000000000212da
- (id)_componentMap;	// IMP=0x000000000002127d
- (id)directoryEnumerator;	// IMP=0x0000000000021212
- (id)payloadExtractorWithDestination:(id)arg1 externalRoot:(id)arg2 error:(id *)arg3;	// IMP=0x00000000000211df
- (id)scriptsExtractorWithDestination:(id)arg1 error:(id *)arg2;	// IMP=0x00000000000211d7
- (id)scriptsSubpath;	// IMP=0x00000000000211cf
- (id)_scriptsDirectory;	// IMP=0x00000000000211c7
- (id)packageInfo;	// IMP=0x00000000000211b6
- (id)packageVersion;	// IMP=0x0000000000021199
- (id)packageIdentifier;	// IMP=0x000000000002117c
- (BOOL)isEqual:(id)arg1;	// IMP=0x0000000000021119
- (unsigned long long)hash;	// IMP=0x00000000000210fc
- (id)description;	// IMP=0x0000000000021094
- (void)dealloc;	// IMP=0x0000000000020fda
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000000020ed3
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000000020eb0
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000000020e0d
- (id)BOMData;	// IMP=0x0000000000026797
- (id)initWithURL:(id)arg1;	// IMP=0x000000000002668f

@end

