//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSDictionary, NSMutableDictionary, NSNumber, NSString, PKPackage, PKPackageRequirements;

@interface PKPackageSpecifier : NSObject <NSSecureCoding, NSCopying>
{
    id <PKPackageReferable> _packageReference;	// 8 = 0x8
    NSString *_prefixPath;	// 16 = 0x10
    NSNumber *_authLevel;	// 24 = 0x18
    long long _options;	// 32 = 0x20
    NSString *_displayName;	// 40 = 0x28
    NSString *_displayVersion;	// 48 = 0x30
    NSString *_externalRootPath;	// 56 = 0x38
    NSMutableDictionary *_userPathByComponentIdent;	// 64 = 0x40
    NSDictionary *_resolvedPathByComponentIdent;	// 72 = 0x48
    NSDictionary *_installPathByComponentIdent;	// 80 = 0x50
    NSString *_packageUniqueHash;	// 88 = 0x58
    PKPackage *_package;	// 96 = 0x60
    PKPackageRequirements *_requirements;	// 104 = 0x68
    NSString *_destinationPath;	// 112 = 0x70
}

+ (BOOL)supportsSecureCoding;	// IMP=0x000000000005373b
+ (id)_adjustedSubpath:(id)arg1 forPackageComponent:(id)arg2 relocatedToPath:(id)arg3;	// IMP=0x000000000005564b
@property(copy) NSString *externalRootPath; // @synthesize externalRootPath=_externalRootPath;
@property long long options; // @synthesize options=_options;
@property(copy) NSString *displayVersion; // @synthesize displayVersion=_displayVersion;
@property(copy) NSString *displayName; // @synthesize displayName=_displayName;
@property(copy) NSString *prefixPath; // @synthesize prefixPath=_prefixPath;
- (id)_packageUniqueHash;	// IMP=0x0000000000053fbe
- (BOOL)_refersToSamePackage:(id)arg1;	// IMP=0x0000000000053f51
@property(copy) NSNumber *authLevel; // @synthesize authLevel=_authLevel;
- (id)package;	// IMP=0x0000000000053db7
@property(retain) id <PKPackageReferable> packageReference; // @synthesize packageReference=_packageReference;
- (void)setUserPath:(id)arg1 forComponentIdentifier:(id)arg2;	// IMP=0x0000000000053b6e
- (id)userPathForComponentIdentifier:(id)arg1;	// IMP=0x0000000000053b49
- (id)_dictionaryRepresentation;	// IMP=0x0000000000053951
- (id)_initWithDictionaryRepresentation:(id)arg1;	// IMP=0x0000000000053746
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000000053507
- (id)initWithCoder:(id)arg1;	// IMP=0x000000000005302f
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000000052dbc
- (unsigned long long)hash;	// IMP=0x0000000000052d86
- (BOOL)isEqual:(id)arg1;	// IMP=0x0000000000052d14
- (id)description;	// IMP=0x0000000000052cb4
- (void)dealloc;	// IMP=0x0000000000052b7c
- (id)initWithPackage:(id)arg1;	// IMP=0x0000000000052a7d
- (id)initWithPackageReference:(id)arg1;	// IMP=0x0000000000052a0c
- (id)_resolvedPrefixPathForPackageComponent:(id)arg1;	// IMP=0x000000000005415b
- (id)_resolvedPrefixPathForPackage;	// IMP=0x00000000000540fd
- (id)_requirements;	// IMP=0x00000000000541d9
- (id)_adjustedSubpath:(id)arg1 forPackageComponent:(id)arg2 previous:(BOOL)arg3;	// IMP=0x0000000000055547
- (id)_previousInstallPathForBundleComponent:(id)arg1;	// IMP=0x00000000000554d7
- (id)_actualInstallPathForBundleComponent:(id)arg1;	// IMP=0x000000000005543d
- (id)_defaultInstallPathForBundleComponent:(id)arg1;	// IMP=0x00000000000553d9
- (void)_resolveInstallPathsForDestination:(id)arg1 replacingPriorResults:(BOOL)arg2;	// IMP=0x00000000000549d2
- (BOOL)_bundleHasOriginalName:(id)arg1;	// IMP=0x0000000000054674
- (id)_onDiskComponentForDestination:(id)arg1 packageComponent:(id)arg2 search:(BOOL)arg3;	// IMP=0x000000000005445a
- (id)__uniquePathForBundle:(id)arg1;	// IMP=0x000000000005599b
- (id)__checkForApplicationConflictForComponent:(id)arg1 provisionalPath:(id)arg2 destination:(id)arg3;	// IMP=0x0000000000055800
- (id)__adjustedInstallPathForComponent:(id)arg1 provisionalPath:(id)arg2 destination:(id)arg3;	// IMP=0x000000000005576e

@end

