//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSRecursiveLock;

@interface PKPackageSourceManager : NSObject
{
    NSMutableArray *_packageSources;	// 8 = 0x8
    NSMutableArray *_packageSourceDistances;	// 16 = 0x10
    NSMutableDictionary *_refToDistanceCache;	// 24 = 0x18
    NSMutableDictionary *_invalidatedPackageReferencesToReasonDict;	// 32 = 0x20
    NSRecursiveLock *_queryLock;	// 40 = 0x28
}

+ (id)_packageReferences:(id)arg1 matchingIdentifier:(id)arg2 version:(id)arg3;	// IMP=0x000000000003de02
+ (id)defaultManager;	// IMP=0x000000000003d9ad
- (void)archiveToCoder:(id)arg1;	// IMP=0x000000000003ee2c
- (void)restoreFromCoder:(id)arg1;	// IMP=0x000000000003eb90
- (void)clearInvalidationForIdentifier:(id)arg1 version:(id)arg2 forReason:(int)arg3;	// IMP=0x000000000003e957
- (void)clearInvalidationListForReason:(int)arg1;	// IMP=0x000000000003e7e7
- (void)clearInvalidationList;	// IMP=0x000000000003e78f
- (void)invalidatePackageReference:(id)arg1 reason:(int)arg2;	// IMP=0x000000000003e705
- (int)distanceForPackageReference:(id)arg1;	// IMP=0x000000000003e599
- (id)bestPackageReferenceMatchingIdentifier:(id)arg1 version:(id)arg2;	// IMP=0x000000000003e510
- (id)_nearestPackageReference:(id)arg1;	// IMP=0x000000000003e46a
- (id)_validSubsetOfPackageReferences:(id)arg1;	// IMP=0x000000000003e12d
- (id)_sortedPackageReferencesMatchingIdentifier:(id)arg1 version:(id)arg2;	// IMP=0x000000000003df04
- (id)allPackageSources;	// IMP=0x000000000003dd9f
- (void)removeSource:(id)arg1;	// IMP=0x000000000003dcfe
- (void)addSource:(id)arg1 distance:(int)arg2;	// IMP=0x000000000003dc60
- (id)description;	// IMP=0x000000000003dbc8
- (void)dealloc;	// IMP=0x000000000003db0e
- (id)init;	// IMP=0x000000000003d9f0

@end

