//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSMutableArray, NSString, PKPackageInfo;

@interface PKPackageChecker : NSObject
{
    NSString *_contentPath;	// 8 = 0x8
    PKPackageInfo *_packageInfo;	// 16 = 0x10
    NSDictionary *_componentMap;	// 24 = 0x18
    NSMutableArray *_checkResults;	// 32 = 0x20
    NSArray *_checkedAttrs;	// 40 = 0x28
}

+ (id)stringForCheckErrorCode:(int)arg1;	// IMP=0x000000000006c6db
+ (id)_defaultCheckedFileAttributes;	// IMP=0x000000000006c330
@property(copy) NSArray *checkedFileAttributes; // @synthesize checkedFileAttributes=_checkedAttrs;
- (BOOL)_isValidScriptAtPath:(id)arg1 error:(id *)arg2;	// IMP=0x000000000006ed8b
- (id)_displayStringForBundleVersion:(id)arg1;	// IMP=0x000000000006ebc2
- (void)_checkBundle:(id)arg1 againstVersion:(id)arg2 usingDisplayPath:(id)arg3;	// IMP=0x000000000006e8bb
- (void)_searchForComponentsInDirectory:(id)arg1 addTo:(id)arg2;	// IMP=0x000000000006e62f
- (BOOL)_shouldValidatePayload;	// IMP=0x000000000006e46e
- (void)_checkScriptsAgainstPackageInfo:(id)arg1;	// IMP=0x000000000006deb1
- (void)_checkPayloadAgainstPackageInfo:(id)arg1;	// IMP=0x000000000006d217
- (void)_checkPayloadAgainstBom;	// IMP=0x000000000006c838
- (id)checkResults;	// IMP=0x000000000006c5e7
- (void)dealloc;	// IMP=0x000000000006c52d
- (id)initWithUnarchivedPackage:(id)arg1 error:(id *)arg2;	// IMP=0x000000000006c384

@end

