//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCache, NSMutableDictionary, NSString;

@interface PKPackageRequirements : NSObject
{
    NSString *_identifier;	// 8 = 0x8
    NSString *_destinationPath;	// 16 = 0x10
    NSCache *_onDiskHashCache;	// 24 = 0x18
    NSMutableDictionary *_actualPathByComponentIdent;	// 32 = 0x20
}

- (id)_checkDigestsForComponent:(id)arg1 allPaths:(BOOL)arg2;	// IMP=0x000000000004bafd
- (id)_encodedDigestForOnDiskFile:(id)arg1;	// IMP=0x000000000004b994
- (id)currentDigestForFile:(id)arg1;	// IMP=0x000000000004b982
- (BOOL)_metForPackageData:(id)arg1 returningError:(id *)arg2;	// IMP=0x000000000004b736
- (BOOL)metForPackageInfo:(id)arg1 returningError:(id *)arg2;	// IMP=0x000000000004b724
- (void)setActualPath:(id)arg1 forComponentIdentifier:(id)arg2;	// IMP=0x000000000004b679
- (id)actualPathForComponentIdentifier:(id)arg1;	// IMP=0x000000000004b654
- (void)dealloc;	// IMP=0x000000000004b5ab
- (id)initWithPackageIdentifier:(id)arg1 destination:(id)arg2;	// IMP=0x000000000004b502

@end

