//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKPatchFilesInstallOperation.h>

@class NSMutableDictionary;

@interface PKPatchAndUpdateInstallOperation : PKPatchFilesInstallOperation
{
    unsigned long long _totalPatchAndUpdateSize;	// 104 = 0x68
    unsigned long long _patchAndUpdateSizeCompleted;	// 112 = 0x70
    void *_bomCopier;	// 120 = 0x78
    void *_bomSys;	// 128 = 0x80
    NSMutableDictionary *_bomCopierOptions;	// 136 = 0x88
}

- (BOOL)_copyItemAtPath:(id)arg1 withAttributes:(id)arg2 toPath:(id)arg3 usingAFSC:(BOOL)arg4 withNewAFSCFormat:(BOOL)arg5 error:(id *)arg6;	// IMP=0x000000000007539a
- (void)main;	// IMP=0x00000000000750b4
- (BOOL)_patchAndUpdateForPackageSpecifier:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000073464
- (BOOL)_shouldUseUpdateVariantForPackageSpecifier:(id)arg1;	// IMP=0x00000000000732de
- (double)estimatedTimeRemaining;	// IMP=0x0000000000073269
- (void)dealloc;	// IMP=0x00000000000731d8
- (id)initWithRequest:(id)arg1 sandbox:(id)arg2 analyzer:(id)arg3;	// IMP=0x0000000000072f3f

@end

