//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@class PKPackageSpecifier;

@interface PKPatchFilesInstallOperation : PKInstallOperation
{
    PKPackageSpecifier *_currentPackageSpecifier;	// 80 = 0x50
    struct CompressionQueueContext_s *_compressionQueue;	// 88 = 0x58
    BOOL _useAFSCByDefault;	// 96 = 0x60
}

- (void)main;	// IMP=0x000000000005eb52
- (BOOL)applyPatchesForPackageSpecifier:(id)arg1 error:(id *)arg2;	// IMP=0x000000000005e764
- (BOOL)patchFileAtSubpath:(id)arg1 inComponent:(id)arg2 atSandboxPrefix:(id)arg3 onDiskPrefix:(id)arg4 withRequirements:(id)arg5 error:(id *)arg6;	// IMP=0x000000000005e259
- (BOOL)shouldPatchFileAtSubpath:(id)arg1 inComponent:(id)arg2;	// IMP=0x000000000005e201
- (void)finishCompressionQueue;	// IMP=0x000000000005e1da
- (void)queueSandboxFileForCompression:(id)arg1;	// IMP=0x000000000005e12e
- (BOOL)isBackwardsIncompatibleCompressionEnabledForCurrentPackage;	// IMP=0x000000000005e0ab
- (BOOL)isCompressionEnabledForCurrentPackage;	// IMP=0x000000000005e030
- (void)createCompressionQueue;	// IMP=0x000000000005dfdb
- (id)currentPackageSpecifier;	// IMP=0x000000000005dfca
- (int)installState;	// IMP=0x000000000005dfbf

@end

