//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"
#import "PKPackageReferable.h"

@class NSDictionary, NSString, NSURL;

@interface PKPackageReference : NSObject <NSSecureCoding, NSCopying, PKPackageReferable>
{
    NSDictionary *_dictionary;	// 8 = 0x8
    NSURL *_baseURL;	// 16 = 0x10
}

+ (BOOL)supportsSecureCoding;	// IMP=0x000000000003d4d1
- (id)digest;	// IMP=0x000000000003d972
- (id)MD5;	// IMP=0x000000000003d94e
- (unsigned long long)fileSize;	// IMP=0x000000000003d911
- (id)version;	// IMP=0x000000000003d8ed
- (id)identifier;	// IMP=0x000000000003d8c9
- (id)URL;	// IMP=0x000000000003d86b
- (id)dictionaryRepresentation;	// IMP=0x000000000003d835
@property(readonly, copy) NSString *description;
- (BOOL)isEqual:(id)arg1;	// IMP=0x000000000003d6ea
@property(readonly) unsigned long long hash;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000000003d61e
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000000003d5bf
- (id)initWithCoder:(id)arg1;	// IMP=0x000000000003d4dc
- (void)dealloc;	// IMP=0x000000000003d44a
- (id)initWithURL:(id)arg1 identifier:(id)arg2 version:(id)arg3 fileSize:(unsigned long long)arg4 MD5:(id)arg5 digest:(id)arg6;	// IMP=0x000000000003d31a
- (id)initWithURL:(id)arg1 identifier:(id)arg2 version:(id)arg3 fileSize:(unsigned long long)arg4 MD5:(id)arg5;	// IMP=0x000000000003d1ff
- (id)initWithDictionaryRepresentation:(id)arg1 baseURL:(id)arg2;	// IMP=0x000000000003d102

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

