//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSURL;

@interface PKProductInfo : NSObject
{
    NSDictionary *_productInfoDictionary;	// 8 = 0x8
    NSURL *_baseURL;	// 16 = 0x10
    NSArray *_cachedPackageReferences;	// 24 = 0x18
}

- (id)baseURL;	// IMP=0x0000000000043e82
- (id)dictionaryRepresentation;	// IMP=0x0000000000043e71
- (id)packageReferences;	// IMP=0x0000000000043d11
- (id)preferredDistributionURL;	// IMP=0x0000000000043b8a
- (id)distributionURLForLocalization:(id)arg1;	// IMP=0x0000000000043af6
- (id)localizations;	// IMP=0x0000000000043a9a
- (id)_distributionsDictionary;	// IMP=0x0000000000043a76
- (id)productVersion;	// IMP=0x0000000000043a52
- (id)productIdentifier;	// IMP=0x0000000000043a2e
- (void)dealloc;	// IMP=0x0000000000043996
- (id)initWithDictionary:(id)arg1 baseURL:(id)arg2;	// IMP=0x00000000000438f5
- (void)setProductIdentifier:(id)arg1 version:(id)arg2;	// IMP=0x00000000000441aa
- (void)setPackageReferences:(id)arg1;	// IMP=0x0000000000044006
- (void)setDistributionURL:(id)arg1 forLocalization:(id)arg2;	// IMP=0x0000000000043f21
- (id)init;	// IMP=0x0000000000043e93

@end

