//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, PKDistribution;

@interface PKProductArchiver : NSObject
{
    NSString *_productPath;	// 8 = 0x8
    NSString *_baselineUnarchivedProduct;	// 16 = 0x10
    CDUnknownBlockType _baselineNameMapper;	// 24 = 0x18
    CDUnknownBlockType _writeActionHandler;	// 32 = 0x20
    PKDistribution *_overrideDistribution;	// 40 = 0x28
    BOOL _copyOwnershipFromOriginalBom;	// 48 = 0x30
    NSDictionary *_options;	// 56 = 0x38
}

@property(retain) NSDictionary *options; // @synthesize options=_options;
@property(copy) NSString *baselineUnarchivedProduct; // @synthesize baselineUnarchivedProduct=_baselineUnarchivedProduct;
@property(retain) PKDistribution *overrideDistribution; // @synthesize overrideDistribution=_overrideDistribution;
@property BOOL copyOwnershipFromOriginalBom; // @synthesize copyOwnershipFromOriginalBom=_copyOwnershipFromOriginalBom;
- (BOOL)_writeScriptsAtPath:(id)arg1 toArchive:(id)arg2 atPath:(id)arg3 error:(id *)arg4;	// IMP=0x000000000006b4ae
- (BOOL)_writePackageAtPath:(id)arg1 toArchive:(id)arg2 atPath:(id)arg3 error:(id *)arg4;	// IMP=0x000000000006abbe
- (BOOL)writeToArchive:(id)arg1 error:(id *)arg2;	// IMP=0x000000000006a7fd
- (void)setWriteActionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000000006a7b1
- (void)setMapBaselineNamesUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000000006a765
- (void)dealloc;	// IMP=0x000000000006a6ad
- (id)initWithUnarchivedProduct:(id)arg1;	// IMP=0x000000000006a5e1

@end

