//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@class PKInstallCommitManager;

@interface PKPrepareForCommitInstallOperation : PKInstallOperation
{
    PKInstallCommitManager *_manager;	// 80 = 0x50
}

- (void)main;	// IMP=0x00000000000838f6
- (int)installState;	// IMP=0x00000000000838eb
- (void)dealloc;	// IMP=0x0000000000083884
- (id)initWithRequest:(id)arg1 sandbox:(id)arg2 analyzer:(id)arg3 manager:(id)arg4;	// IMP=0x000000000008380b

@end

