//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PKArchive;

@interface PKProductUnarchiver : NSObject
{
    PKArchive *_productArchive;	// 8 = 0x8
    BOOL _useIndexBom;	// 16 = 0x10
    BOOL _preserveExtAttrsAndACLs;	// 17 = 0x11
}

@property BOOL preserveExtAttrsAndACLs; // @synthesize preserveExtAttrsAndACLs=_preserveExtAttrsAndACLs;
@property BOOL useIndexBom; // @synthesize useIndexBom=_useIndexBom;
- (BOOL)_unarchiveCPIOToPath:(id)arg1 error:(id *)arg2;	// IMP=0x000000000006a00a
- (BOOL)_unarchiveNonCPIOToPath:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000069df4
- (BOOL)unarchiveToPath:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000069bc4
- (void)dealloc;	// IMP=0x0000000000069b5d
- (id)initWithProductURL:(id)arg1;	// IMP=0x0000000000069a23

@end

