//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@class NSString, PKPackageSpecifier;

@interface PKRelocateComponentsInstallOperation : PKInstallOperation
{
    PKPackageSpecifier *_currentPackageSpecifier;	// 80 = 0x50
    NSString *_currentOldBundlePath;	// 88 = 0x58
    NSString *_currentNewBundlePath;	// 96 = 0x60
}

- (void)main;	// IMP=0x000000000005fa64
- (BOOL)_localizeParentFolderForBundleAtPath:(id)arg1;	// IMP=0x000000000005f59d
- (BOOL)_moveRelocatedComponentsForPackageSpecifier:(id)arg1 error:(id *)arg2;	// IMP=0x000000000005ef65
- (id)messageTracerTernarySignature;	// IMP=0x000000000005eeb6
- (id)messageTracerComment;	// IMP=0x000000000005edd9
- (id)messageTracerDomain;	// IMP=0x000000000005edcc
- (id)currentPackageSpecifier;	// IMP=0x000000000005edbb
- (int)installState;	// IMP=0x000000000005edb0

@end

