//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface PKReceipt : NSObject
{
    NSMutableDictionary *_receiptDictionary;	// 8 = 0x8
    NSString *_bomPath;	// 16 = 0x10
    void *_cachedBOM;	// 24 = 0x18
    NSString *_bundlePath;	// 32 = 0x20
    BOOL _isSecure;	// 40 = 0x28
}

+ (void)_clearCache;	// IMP=0x000000000002dc38
+ (id)receiptsAtPath:(id)arg1;	// IMP=0x000000000002eceb
+ (id)receiptWithPackageFileName:(id)arg1 volume:(id)arg2;	// IMP=0x000000000002eb37
+ (id)receiptWithIdentifier:(id)arg1 volume:(id)arg2;	// IMP=0x000000000002e983
+ (id)receiptsOnVolumeAtPath:(id)arg1;	// IMP=0x000000000002e8b8
+ (id)_findReceiptsOnVolumeAtPath:(id)arg1;	// IMP=0x000000000002e5e7
+ (id)__findBundleReceiptsFromDirectory:(id)arg1;	// IMP=0x000000000002e39e
+ (id)__findReceiptsFromBOMsDirectory:(id)arg1;	// IMP=0x000000000002e155
+ (id)_receiptDictionaryPathFromBOMPath:(id)arg1;	// IMP=0x000000000002f93e
+ (id)_searchDirectoriesForBundleReceiptsOnDestination:(id)arg1;	// IMP=0x000000000002f75e
+ (id)_searchDirectoriesForBOMReceiptsOnDestination:(id)arg1 returningSecureIndexes:(id *)arg2;	// IMP=0x000000000002f572
+ (id)_receiptsDirectoryPathForSandboxRoot:(id)arg1 destination:(id)arg2;	// IMP=0x000000000002f452
+ (id)_receiptsDirectoryPathForDestination:(id)arg1;	// IMP=0x000000000002f396
+ (id)_systemContentReceiptsDirectoryPathForDestination:(id)arg1;	// IMP=0x000000000002f377
+ (id)_systemContentReceiptsDirectoryPathForSandboxRoot:(id)arg1 destination:(id)arg2;	// IMP=0x000000000002f358
+ (void)_clearCacheWithNotification:(id)arg1;	// IMP=0x00000000000300ee
+ (void)_clearCacheInOtherProcesses;	// IMP=0x0000000000030021
+ (void)_clearCacheLocally;	// IMP=0x0000000000030008
+ (id)_sharedReceiptsCache;	// IMP=0x000000000002ff88
- (id)installPrefixPath;	// IMP=0x000000000002e131
- (id)installProcessName;	// IMP=0x000000000002e10d
- (id)installDate;	// IMP=0x000000000002e0e9
- (id)packageVersion;	// IMP=0x000000000002e0c5
- (id)packageIdentifier;	// IMP=0x000000000002e0a1
- (id)description;	// IMP=0x000000000002e041
- (id)initWithBundlePkgPath:(id)arg1;	// IMP=0x000000000002de04
- (id)initWithBOMPath:(id)arg1;	// IMP=0x000000000002dc66
- (void)dealloc;	// IMP=0x000000000002db96
- (id)init;	// IMP=0x000000000002db08
- (void)_setSecure:(BOOL)arg1;	// IMP=0x000000000002ff75
- (BOOL)_isSecure;	// IMP=0x000000000002ff61
- (BOOL)_updateACLsOfItemAtPath:(id)arg1 withFile:(id)arg2;	// IMP=0x000000000002fe7e
- (BOOL)_updateSHA1ChecksumOfItemAtPath:(id)arg1 withFile:(id)arg2;	// IMP=0x000000000002fe1a
- (void)_setACLString:(id)arg1 forItemAtPath:(id)arg2;	// IMP=0x000000000002fd53
- (id)_ACLStringOfItemAtPath:(id)arg1;	// IMP=0x000000000002fd02
- (void)_setSHA1ChecksumData:(id)arg1 forItemAtPath:(id)arg2;	// IMP=0x000000000002fc3b
- (id)_SHA1ChecksumDataOfItemAtPath:(id)arg1;	// IMP=0x000000000002fbea
- (id)_attributesOfItemAtPath:(id)arg1;	// IMP=0x000000000002fbb9
- (id)_directoryEnumerator;	// IMP=0x000000000002fb8e
- (void)_freeBOM;	// IMP=0x000000000002fb5c
- (id)_BOM;	// IMP=0x000000000002fac8
- (id)receiptStoragePaths;	// IMP=0x000000000002f9ac
- (void)_setInstallPrefixPath:(id)arg1;	// IMP=0x000000000002f914
- (void)_setInstallProcessName:(id)arg1;	// IMP=0x000000000002f8ea
- (void)_setPackageName:(id)arg1;	// IMP=0x000000000002f8c0
- (id)_packageName;	// IMP=0x000000000002f896
- (void)_setPackageGroups:(id)arg1;	// IMP=0x000000000002f834
- (id)packageGroups;	// IMP=0x000000000002f80a
- (BOOL)_removeReceiptInDirectory:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000030176

@end

