//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PKScript : NSObject
{
    NSString *_path;	// 8 = 0x8
    double _estimatedRunningTime;	// 16 = 0x10
}

@property double estimatedRunningTime; // @synthesize estimatedRunningTime=_estimatedRunningTime;
@property(copy) NSString *path; // @synthesize path=_path;
- (void)dealloc;	// IMP=0x00000000000452b0
- (id)initWithPath:(id)arg1 estimatedRunningTime:(double)arg2;	// IMP=0x0000000000045221
- (id)initWithPath:(id)arg1;	// IMP=0x0000000000045207

@end

