//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@interface PKSetupDeferredInstallOperation : PKInstallOperation
{
}

- (void)main;	// IMP=0x0000000000061b59
- (BOOL)_arrangeForDeferredInstallReturningError:(id *)arg1;	// IMP=0x000000000006158b
- (int)installState;	// IMP=0x0000000000061580

@end

