//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@interface PKShoveInstallOperation : PKInstallOperation
{
}

- (void)main;	// IMP=0x000000000006261b
- (BOOL)_shoveExtractedRootOntoDestinationReturningError:(id *)arg1;	// IMP=0x0000000000062146
- (void)_moveActiveDYLDCacheIfNeeded;	// IMP=0x0000000000061e1f
- (id)messageTracerComment;	// IMP=0x0000000000061e12
- (id)messageTracerDomain;	// IMP=0x0000000000061e05
- (int)installState;	// IMP=0x0000000000061dfa
- (id)initWithRequest:(id)arg1 sandbox:(id)arg2 analyzer:(id)arg3;	// IMP=0x0000000000061bba

@end

