//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface PKSigningIdentity : NSObject
{
    struct OpaqueSecIdentityRef *_identity;	// 8 = 0x8
    NSMutableArray *_supportingCerts;	// 16 = 0x10
    NSString *_keychainSpec;	// 24 = 0x18
}

+ (id)_identitiesMatchingPrefix:(id)arg1 policy:(struct OpaqueSecPolicyRef *)arg2 fromKeychain:(id)arg3;	// IMP=0x0000000000078614
+ (id)_validIdentitiesMatchingPrefix:(id)arg1 fromKeychain:(id)arg2 forCodeSigning:(BOOL)arg3 didExcludeWrongIdentities:(char *)arg4;	// IMP=0x0000000000078375
+ (struct OpaqueSecKeychainRef *)_copyKeychainWithPath:(id)arg1;	// IMP=0x00000000000780fd
+ (id)commonNameForCertificate:(struct OpaqueSecCertificateRef *)arg1;	// IMP=0x000000000007793c
+ (id)allSigningIdentitiesWithPrefix:(id)arg1 fromKeychain:(id)arg2 forCodeSigning:(BOOL)arg3;	// IMP=0x0000000000077927
+ (id)allSigningIdentitiesWithPrefix:(id)arg1 fromKeychain:(id)arg2;	// IMP=0x000000000007790f
+ (id)bestSigningIdentityFromString:(id)arg1 fromKeychain:(id)arg2 forCodeSigning:(BOOL)arg3 error:(id *)arg4;	// IMP=0x0000000000077557
+ (id)bestSigningIdentityFromString:(id)arg1 fromKeychain:(id)arg2 error:(id *)arg3;	// IMP=0x000000000007753c
+ (id)bestSigningIdentityFromString:(id)arg1 fromKeychain:(id)arg2;	// IMP=0x0000000000077524
- (unsigned long long)_levelOfMatch:(id)arg1;	// IMP=0x0000000000078b0a
- (id)_sha1AsString;	// IMP=0x00000000000789ec
- (id)_initWithIdentityRef:(struct OpaqueSecIdentityRef *)arg1 keychainSpec:(id)arg2;	// IMP=0x000000000007805c
- (id)keychainPath;	// IMP=0x0000000000077f70
- (BOOL)addIntermediateCertificateWithCommonName:(id)arg1;	// IMP=0x0000000000077db7
- (id)supportingCertificateRefs;	// IMP=0x0000000000077c30
- (BOOL)shouldUseTSAByDefault;	// IMP=0x0000000000077b99
- (id)name;	// IMP=0x0000000000077b09
- (struct OpaqueSecIdentityRef *)identityRef;	// IMP=0x0000000000077af8
- (id)description;	// IMP=0x0000000000077a98
- (BOOL)isEqual:(id)arg1;	// IMP=0x0000000000077a26
- (void)dealloc;	// IMP=0x000000000007798a

@end

