//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKXARArchive.h>

@class NSFileHandle, NSMutableDictionary, NSString;

@interface PKStreamingXARArchive : PKXARArchive
{
    NSMutableDictionary *_streamingState;	// 32 = 0x20
    NSFileHandle *_underlyingArchiveFileHandle;	// 40 = 0x28
    NSString *_underlyingArchiveFileName;	// 48 = 0x30
}

+ (void)_createStreamingPlaceholderAtPath:(id)arg1 md5Hashes:(id)arg2 hashedChunkSize:(unsigned long long)arg3 resumptionOffset:(unsigned long long *)arg4 error:(id *)arg5;	// IMP=0x0000000000072ad8
+ (BOOL)_streamingPlaceholderExistsAtPath:(id)arg1 md5Hashes:(id)arg2 hashedChunkSize:(unsigned long long)arg3;	// IMP=0x0000000000072a03
+ (void)_writeSteamingPlaceholderState:(id)arg1 atPath:(id)arg2;	// IMP=0x00000000000729c3
+ (id)_streamingPlaceholderStateAtPath:(id)arg1;	// IMP=0x0000000000072952
- (void)setFinished:(BOOL)arg1;	// IMP=0x0000000000072ef8
- (BOOL)isFinished;	// IMP=0x0000000000072ebb
- (void)setSuspended:(BOOL)arg1;	// IMP=0x0000000000072e74
- (BOOL)isSuspended;	// IMP=0x0000000000072e37
- (void)setResumptionOffset:(unsigned long long)arg1;	// IMP=0x0000000000072df0
- (unsigned long long)resumptionOffset;	// IMP=0x0000000000072db3
- (id)md5Hashes;	// IMP=0x0000000000072d6a
- (unsigned long long)hashedChunkSize;	// IMP=0x0000000000072d2d
- (id)finishStream;	// IMP=0x000000000007291e
- (id)suspendStream;	// IMP=0x000000000007286e
- (id)supplyBytes:(id)arg1;	// IMP=0x0000000000072567
- (BOOL)_verifyMD5Hash:(id)arg1 forByteRange:(struct _NSRange)arg2 error:(id *)arg3;	// IMP=0x000000000007229d
- (id)_createOrOpenFileForUpdatingAtPath:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000072172
- (id)_underlyingArchivePath;	// IMP=0x000000000007213c
- (void)dealloc;	// IMP=0x00000000000720a4
- (id)initForReadingFromPath:(id)arg1;	// IMP=0x0000000000071f5c

@end

