//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@class NSString;

@interface PKUpdateEFWCacheInstallOperation : PKInstallOperation
{
    NSString *_cacheTool;	// 80 = 0x50
}

- (void)main;	// IMP=0x0000000000071b1b
- (BOOL)_cacheEmbeddedContentForBundleAtPath:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000071a27
- (int)installState;	// IMP=0x0000000000071a1c
- (void)dealloc;	// IMP=0x00000000000719b5
- (id)initWithRequest:(id)arg1 sandbox:(id)arg2 analyzer:(id)arg3;	// IMP=0x0000000000071889

@end

