//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PKURLConnection : NSObject
{
}

+ (void)sendAsynchronousRequest:(id)arg1 notifyOn:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000000003f639
+ (id)sendSynchronousRequest:(id)arg1 returningResponse:(id *)arg2 error:(id *)arg3;	// IMP=0x000000000003f336
+ (void)finishAuthenticationChallenge:(id)arg1 usingCredential:(id)arg2;	// IMP=0x000000000003f2e3
+ (void)finishAuthenticationChallenge:(id)arg1 usingCredential:(id)arg2 shouldContinue:(BOOL)arg3;	// IMP=0x000000000003f291
+ (void)didReceiveAuthenticationChallenge:(id)arg1;	// IMP=0x000000000003f103
+ (void)setUserAgent:(id)arg1;	// IMP=0x000000000003f0c3
+ (id)userAgent;	// IMP=0x000000000003f0b6
+ (void)setSharedAuthenticationHandler:(id)arg1;	// IMP=0x000000000003f07b

@end

