//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKDownload.h>

#import "NSURLConnectionDelegate.h"
#import "NSURLDownloadDelegate.h"

@class NSString, NSURLDownload;

@interface PKURLDownload : PKDownload <NSURLDownloadDelegate, NSURLConnectionDelegate>
{
    NSURLDownload *_urlDownload;	// 32 = 0x20
}

+ (BOOL)canDownloadWithResumeData:(id)arg1;	// IMP=0x00000000000657f4
+ (BOOL)canDownloadURL:(id)arg1;	// IMP=0x00000000000657bf
- (void)download:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x000000000006608d
- (void)downloadDidFinish:(id)arg1;	// IMP=0x0000000000066032
- (void)download:(id)arg1 didReceiveDataOfLength:(unsigned long long)arg2;	// IMP=0x0000000000065fd4
- (void)download:(id)arg1 didReceiveResponse:(id)arg2;	// IMP=0x0000000000065ef4
- (void)download:(id)arg1 willResumeWithResponse:(id)arg2 fromByte:(long long)arg3;	// IMP=0x0000000000065db6
- (id)download:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;	// IMP=0x0000000000065d40
- (void)download:(id)arg1 didCancelAuthenticationChallenge:(id)arg2;	// IMP=0x0000000000065ce2
- (void)download:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;	// IMP=0x0000000000065c84
- (BOOL)_wantHTTPLogging;	// IMP=0x0000000000065c31
- (void)setDeletesFileUponFailure:(BOOL)arg1;	// IMP=0x0000000000065c14
- (void)setDestination:(id)arg1 allowOverwrite:(BOOL)arg2;	// IMP=0x0000000000065bf7
- (id)resumeData;	// IMP=0x0000000000065b71
- (id)sourceURL;	// IMP=0x0000000000065b3b
- (id)sourcePath;	// IMP=0x0000000000065af9
- (void)cancel;	// IMP=0x0000000000065adc
- (id)initWithResumeData:(id)arg1 destination:(id)arg2 delegate:(id)arg3;	// IMP=0x0000000000065989
- (id)initWithURL:(id)arg1 delegate:(id)arg2;	// IMP=0x000000000006584e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

