//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@class PKPackageSpecifier;

@interface PKWriteMASReceiptInstallOperation : PKInstallOperation
{
    PKPackageSpecifier *_currentPackageSpecifier;	// 80 = 0x50
}

- (void)main;	// IMP=0x00000000000768b7
- (BOOL)_addAppStoreReceipt:(id)arg1 forPackageSpecifier:(id)arg2 error:(id *)arg3;	// IMP=0x000000000007643c
- (id)_receiptPathInBundle:(id)arg1;	// IMP=0x00000000000763bb
- (int)installState;	// IMP=0x00000000000763b0

@end

