//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@class PKPackageSpecifier;

@interface PKWriteReceiptsInstallOperation : PKInstallOperation
{
    PKPackageSpecifier *_currentPackageSpecifier;	// 80 = 0x50
    BOOL _inSandbox;	// 88 = 0x58
}

- (void)main;	// IMP=0x0000000000063cd5
- (BOOL)_saveReceiptForPackageSpecifier:(id)arg1 withMasterBOM:(id)arg2 error:(id *)arg3;	// IMP=0x0000000000063586
- (id)_newMasterBOMIfEnabled;	// IMP=0x0000000000063364
- (BOOL)_shouldWriteReceiptForPackageSpecifier:(id)arg1;	// IMP=0x0000000000063246
- (id)messageTracerComment;	// IMP=0x00000000000631f1
- (id)messageTracerDomain;	// IMP=0x00000000000631e4
- (id)currentPackageSpecifier;	// IMP=0x00000000000631d3
- (int)installState;	// IMP=0x00000000000631c8
- (id)initWithRequest:(id)arg1 sandbox:(id)arg2 analyzer:(id)arg3 writeInSandbox:(BOOL)arg4;	// IMP=0x0000000000062f4d

@end

