//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKMutableArchive.h>

@class NSString;

@interface PKXARArchive : PKMutableArchive
{
    NSString *_archivePath;	// 8 = 0x8
    struct __xar_t *_xarPtr;	// 16 = 0x10
    BOOL _skipsVerify;	// 24 = 0x18
}

+ (id)_fileAttributeForXARProperty:(char *)arg1 fileAttributeKey:(id)arg2;	// IMP=0x000000000000da66
+ (id)_fileAttributeKeyForXARFileType:(id)arg1;	// IMP=0x000000000000d957
+ (id)_fileAttributeKeyForXARPropertyName:(id)arg1;	// IMP=0x000000000000d7d9
- (id)__openOrVerifyErrorForArchiveEntry:(id)arg1;	// IMP=0x000000000000e14b
- (unsigned long long)_fileOffsetForPath:(id)arg1 error:(id *)arg2;	// IMP=0x000000000000e064
- (BOOL)fileExistsAtPath:(id)arg1;	// IMP=0x000000000000e046
- (BOOL)verifyReturningError:(id *)arg1;	// IMP=0x000000000000df2f
- (id)fileAttributesAtPath:(id)arg1;	// IMP=0x000000000000dc64
- (BOOL)_extractFile:(id)arg1 toPath:(id)arg2 error:(id *)arg3;	// IMP=0x000000000000d6bd
- (id)dataForPath:(id)arg1;	// IMP=0x000000000000d5c1
- (id)enumeratorAtPath:(id)arg1;	// IMP=0x000000000000d540
- (struct __xar_file_t *)_fileStructForSubpath:(id)arg1 error:(id *)arg2;	// IMP=0x000000000000d425
- (BOOL)_xarFileIsValid:(struct __xar_file_t *)arg1;	// IMP=0x000000000000d3b2
- (struct __xar_t *)_xar;	// IMP=0x000000000000d340
- (BOOL)closeArchive;	// IMP=0x000000000000d30a
- (id)archiveDigest;	// IMP=0x000000000000d148
- (id)archivePath;	// IMP=0x000000000000d137
- (void)_setSkipsVerifyIfUnsigned:(BOOL)arg1;	// IMP=0x000000000000d127
- (void)dealloc;	// IMP=0x000000000000d0ae
- (id)initForReadingFromPath:(id)arg1;	// IMP=0x000000000000d009
- (id)archiveSignatureDate;	// IMP=0x000000000000ec68
- (id)archiveSignatures;	// IMP=0x000000000000eada

@end

