//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKArchiveSignature.h>

@interface PKXARArchiveSignature : PKArchiveSignature
{
    struct __xar_signature_t *_sig;	// 16 = 0x10
}

- (BOOL)_hasSigningCertificate:(struct OpaqueSecCertificateRef *)arg1;	// IMP=0x000000000000f7af
- (id)signatureDataReturningAlgorithm:(id *)arg1;	// IMP=0x000000000000f6ea
- (id)signedDataReturningAlgorithm:(id *)arg1;	// IMP=0x000000000000f627
- (id)algorithmType;	// IMP=0x000000000000f5ed
- (id)certificateRefs;	// IMP=0x000000000000f202
- (id)initWithXARSignature:(struct __xar_signature_t *)arg1;	// IMP=0x000000000000f1a3

@end

