//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PackageKit/PKInstallOperation.h>

@class PKInstallTask;

@interface PKXPCCacheInstallOperation : PKInstallOperation
{
    PKInstallTask *_currentTask;	// 80 = 0x50
    BOOL _inSandbox;	// 88 = 0x58
}

- (void)cancel;	// IMP=0x0000000000084750
- (void)main;	// IMP=0x000000000008462e
- (BOOL)_rebuildXPCServiceCacheInSandboxReturningError:(id *)arg1;	// IMP=0x00000000000843b3
- (BOOL)_triggerRebuildOfXPCServiceCacheOnNextRebootReturningError:(id *)arg1;	// IMP=0x000000000008429e
- (BOOL)_installingToYosemiteOrAbove;	// IMP=0x00000000000840e1
- (id)_pathForTool:(id)arg1;	// IMP=0x0000000000084010
- (int)installState;	// IMP=0x0000000000084005
- (BOOL)_shouldRebuildXPCServiceCache;	// IMP=0x0000000000083f17
- (id)description;	// IMP=0x0000000000083e92
- (id)initWithRequest:(id)arg1 sandbox:(id)arg2 analyzer:(id)arg3 updateInSandbox:(BOOL)arg4;	// IMP=0x0000000000083df8

@end

